-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.alumni_chapter (
  id integer GENERATED ALWAYS AS IDENTITY NOT NULL,
  chapter1 numeric,
  chapter2 numeric,
  chapter3 numeric,
  remarks text,
  CONSTRAINT alumni_chapter_pkey PRIMARY KEY (id),
  CONSTRAINT alumni_chapter_id_fkey FOREIGN KEY (id) REFERENCES public.tbl_alumni(alumniid)
);
-- Table: public.alumni_memberships

-- DROP TABLE IF EXISTS public.alumni_memberships;

CREATE TABLE IF NOT EXISTS public.alumni_memberships
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    alumniid integer NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    gym_membership_month text COLLATE pg_catalog."default",
    swimmingpool_membership_month text COLLATE pg_catalog."default",
    reason text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    CONSTRAINT alumni_memberships_pkey PRIMARY KEY (id),
    CONSTRAINT alumni_memberships_alumniid_fkey FOREIGN KEY (alumniid)
        REFERENCES public.tbl_alumni (alumniid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.alumni_memberships
    OWNER to postgres;
-- Table: public.alumni_scholarships

-- DROP TABLE IF EXISTS public.alumni_scholarships;

CREATE TABLE IF NOT EXISTS public.alumni_scholarships
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    kinship_firstname text COLLATE pg_catalog."default",
    kinship_lastname text COLLATE pg_catalog."default",
    kinship_cnic text COLLATE pg_catalog."default",
    apply_for text COLLATE pg_catalog."default",
    degree_title text COLLATE pg_catalog."default",
    status text COLLATE pg_catalog."default",
    reason text COLLATE pg_catalog."default",
    CONSTRAINT alumni_scholarships_pkey PRIMARY KEY (id),
    CONSTRAINT alumni_scholarships_id_fkey FOREIGN KEY (id)
        REFERENCES public.tbl_alumni (alumniid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.alumni_scholarships
    OWNER to postgres;

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.alumni_scholarships
    OWNER to postgres;
CREATE TABLE public.alumnichapterslocation (
  chapterid integer NOT NULL DEFAULT nextval('alumnichapterslocation_chapterid_seq'::regclass),
  categoryname character varying,
  chaptercode character varying,
  chaptertitle character varying,
  chapterlocation character varying NOT NULL,
  chapterwhatsapp character varying,
  CONSTRAINT alumnichapterslocation_pkey PRIMARY KEY (chapterid)
);
CREATE TABLE public.chapter_leadership (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  post text,
  status text DEFAULT 'pending'::text,
  rejection_reason text,
  updated_at timestamp with time zone DEFAULT now(),
  alumniid integer,
  CONSTRAINT chapter_leadership_pkey PRIMARY KEY (id)
);
CREATE TABLE public.leadership_form_settings (
  id integer NOT NULL DEFAULT nextval('leadership_form_settings_id_seq'::regclass),
  form_type character varying NOT NULL UNIQUE,
  is_enabled boolean NOT NULL DEFAULT true,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_by integer,
  CONSTRAINT leadership_form_settings_pkey PRIMARY KEY (id),
  CONSTRAINT leadership_form_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.tbl_users(userid)
);
CREATE TABLE public.newsletters (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  title text,
  date date,
  image text,
  link text,
  CONSTRAINT newsletters_pkey PRIMARY KEY (id)
);
CREATE TABLE public.staging_alumni_import (
  alumniemail character varying,
  alumniname text,
  gender text,
  contactno text,
  city text,
  country text,
  work_city text,
  work_country text,
  designation text,
  nameoforganization text,
  imported_at timestamp without time zone DEFAULT now(),
  major text,
  passing text,
  school text,
  job text,
  sapid text
);
-- Table: public.tbl_alumni

-- DROP TABLE IF EXISTS public.tbl_alumni;

CREATE TABLE IF NOT EXISTS public.tbl_alumni
(
    alumniid integer NOT NULL DEFAULT nextval('tbl_alumni_alumniid_seq'::regclass),
    alumniemail character varying(150) COLLATE pg_catalog."default",
    password text COLLATE pg_catalog."default",
    todaydate timestamp without time zone,
    registrationno character varying(20) COLLATE pg_catalog."default",
    sapid character varying(20) COLLATE pg_catalog."default",
    alumniname character varying(200) COLLATE pg_catalog."default",
    gender character varying(50) COLLATE pg_catalog."default",
    fathername character varying(200) COLLATE pg_catalog."default",
    dateofbirth character varying(50) COLLATE pg_catalog."default",
    maritalstatus character varying(50) COLLATE pg_catalog."default",
    cnicpassport character varying(50) COLLATE pg_catalog."default",
    contactno character varying(50) COLLATE pg_catalog."default",
    contactno1 character varying(50) COLLATE pg_catalog."default",
    personalemail character varying(100) COLLATE pg_catalog."default",
    universityemail character varying(100) COLLATE pg_catalog."default",
    country character varying(50) COLLATE pg_catalog."default",
    province character varying(50) COLLATE pg_catalog."default",
    city character varying(50) COLLATE pg_catalog."default",
    address character varying(250) COLLATE pg_catalog."default",
    academicsession character varying(50) COLLATE pg_catalog."default",
    degreetitle character varying(300) COLLATE pg_catalog."default",
    cgpa double precision,
    yearofstarting integer,
    yearofending integer,
    facultyname character varying(100) COLLATE pg_catalog."default",
    campusname character varying(100) COLLATE pg_catalog."default",
    departmentname character varying(300) COLLATE pg_catalog."default",
    majorsubject character varying(100) COLLATE pg_catalog."default",
    industry text COLLATE pg_catalog."default",
    employeed text COLLATE pg_catalog."default",
    nameoforganization character varying(100) COLLATE pg_catalog."default",
    designation character varying(100) COLLATE pg_catalog."default",
    totalyearsofexpereince character varying(10) COLLATE pg_catalog."default",
    officialemail character varying(100) COLLATE pg_catalog."default",
    officialnumber character varying(50) COLLATE pg_catalog."default",
    work_city text COLLATE pg_catalog."default",
    supervisordesignation character varying(100) COLLATE pg_catalog."default",
    work_country text COLLATE pg_catalog."default",
    supervisornumber character varying(50) COLLATE pg_catalog."default",
    image1 character varying(200) COLLATE pg_catalog."default",
    cv character varying(200) COLLATE pg_catalog."default",
    aboutme text COLLATE pg_catalog."default",
    lasttimelogin character varying(50) COLLATE pg_catalog."default",
    logincount integer,
    verify character varying COLLATE pg_catalog."default",
    emailsendcount smallint,
    emailsendstatus character varying(100) COLLATE pg_catalog."default",
    createddatetime character varying(50) COLLATE pg_catalog."default",
    facebook character varying(300) COLLATE pg_catalog."default",
    instagram character varying(300) COLLATE pg_catalog."default",
    youtube character varying(300) COLLATE pg_catalog."default",
    linkedin character varying(300) COLLATE pg_catalog."default",
    datasource character varying(50) COLLATE pg_catalog."default",
    alumnistatus character varying(50) COLLATE pg_catalog."default",
    higher_education_institute_name text COLLATE pg_catalog."default",
    degree_title text COLLATE pg_catalog."default",
    is_scholarship text COLLATE pg_catalog."default",
    higher_education_program text COLLATE pg_catalog."default",
    father_cnic text COLLATE pg_catalog."default",
    image2 text COLLATE pg_catalog."default",
    association_id bigint,
    association_job integer,
    chapter_leadership bigint,
    organization_address text COLLATE pg_catalog."default",
    higher_education_institute_country text COLLATE pg_catalog."default",
    higher_education_institute_province text COLLATE pg_catalog."default",
    higher_education_institute_city text COLLATE pg_catalog."default",
    about text COLLATE pg_catalog."default",
    category text COLLATE pg_catalog."default",
    faculty bigint,
    department bigint,
    program bigint,
    contactno1show text COLLATE pg_catalog."default",
    personalemailshow text COLLATE pg_catalog."default",
    alumni_consent_info boolean,
    alumni_consent_pic boolean,
    CONSTRAINT tbl_alumni_pkey PRIMARY KEY (alumniid),
    CONSTRAINT tbl_alumni_association_id_fkey FOREIGN KEY (association_id)
        REFERENCES public.tbl_associations (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT tbl_alumni_association_job_fkey FOREIGN KEY (association_job)
        REFERENCES public.tblalumniassociation (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT tbl_alumni_chapter_leadership_fkey FOREIGN KEY (chapter_leadership)
        REFERENCES public.chapter_leadership (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT tbl_alumni_department_fkey FOREIGN KEY (department)
        REFERENCES public.tbl_departments (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT tbl_alumni_faculty_fkey FOREIGN KEY (faculty)
        REFERENCES public.tbl_faculties (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT tbl_alumni_program_fkey FOREIGN KEY (program)
        REFERENCES public.tbl_programs (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tbl_alumni
    OWNER to postgres;
-- Table: public.tbl_departments

-- DROP TABLE IF EXISTS public.tbl_departments;

CREATE TABLE IF NOT EXISTS public.tbl_departments
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    department_name text COLLATE pg_catalog."default",
    faculty_id bigint,
    department_code text COLLATE pg_catalog."default",
    CONSTRAINT uol_departments_pkey PRIMARY KEY (id),
    CONSTRAINT tbl_departments_faculty_id_fkey FOREIGN KEY (faculty_id)
        REFERENCES public.tbl_faculties (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tbl_departments
    OWNER to postgres;
CREATE TABLE public.tbl_events (
  id integer NOT NULL DEFAULT nextval('tbl_events_id_seq'::regclass),
  category character varying,
  title character varying,
  shortdescription character varying,
  longdescription text,
  fromdate date,
  todate date,
  eventtime character varying,
  image1 character varying NOT NULL,
  image2 character varying,
  image3 character varying,
  image4 character varying,
  image5 character varying,
  parent_type text CHECK (parent_type = ANY (ARRAY['chapter'::text, 'association'::text])),
  parent_id bigint,
  chapter_id bigint,
  association_id bigint,
  type text,
  CONSTRAINT tbl_events_pkey PRIMARY KEY (id)
);

-- Table: public.tbl_courses

-- DROP TABLE IF EXISTS public.tbl_courses;

CREATE TABLE IF NOT EXISTS public.tbl_courses
(
    course_name text COLLATE pg_catalog."default",
    id bigint NOT NULL,
    course_code numeric,
    CONSTRAINT tbl_courses_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tbl_courses
    OWNER to postgres;

-- Table: public.tbl_faculties

-- DROP TABLE IF EXISTS public.tbl_faculties;

CREATE TABLE IF NOT EXISTS public.tbl_faculties
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    faculty_name text COLLATE pg_catalog."default",
    CONSTRAINT uol_faculties_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tbl_faculties
    OWNER to postgres;
-- Table: public.tbl_programs

-- DROP TABLE IF EXISTS public.tbl_programs;

CREATE TABLE IF NOT EXISTS public.tbl_programs
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    program_name text COLLATE pg_catalog."default",
    department_id bigint,
    program_abv text COLLATE pg_catalog."default",
    CONSTRAINT tbl_programs_pkey PRIMARY KEY (id),
    CONSTRAINT uniq_program_department UNIQUE (department_id, program_name),
    CONSTRAINT tbl_programs_department_id_fkey FOREIGN KEY (department_id)
        REFERENCES public.tbl_departments (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tbl_programs
    OWNER to postgres;

ALTER TABLE IF EXISTS public.tbl_programs
    ENABLE ROW LEVEL SECURITY;

CREATE TABLE public.tbl_users (
  userid integer NOT NULL DEFAULT nextval('tbl_users_userid_seq'::regclass),
  email text,
  password text,
  firstname character varying,
  lastname character varying,
  department character varying,
  type character varying,
  blocked boolean,
  lastlogindatetime character varying,
  CONSTRAINT tbl_users_pkey PRIMARY KEY (userid)
);
CREATE TABLE public.tblalumniassociation (
  id integer NOT NULL DEFAULT nextval('tblalumniassociation_id_seq'::regclass),
  q3 character varying,
  q2 character varying,
  q2others character varying,
  q4 character varying,
  q5 character varying,
  q6 character varying,
  q7 character varying,
  createddatetime timestamp without time zone,
  status character varying DEFAULT 'pending'::character varying,
  alumni_id integer,
  CONSTRAINT tblalumniassociation_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tblalumnistories (
  alumniid integer NOT NULL,
  alumnistories text,
  story_image character varying,
  status character varying,
  createdat timestamp without time zone,
  storytitle text,
  id integer NOT NULL DEFAULT nextval('tblalumnistories_id_seq'::regclass),
  CONSTRAINT tblalumnistories_pkey PRIMARY KEY (id),
  CONSTRAINT tblalumnistories_alumniid_fkey FOREIGN KEY (alumniid) REFERENCES public.tbl_alumni(alumniid)
);
CREATE TABLE public.tblalumnitalks (
  id integer NOT NULL DEFAULT nextval('tblalumnitalks_id_seq'::regclass),
  alumniid integer NOT NULL,
  alumnitalks character varying,
  mentorshipprogram character varying,
  topic text,
  date_1 date,
  timings_1 text,
  activity text,
  linkedin character varying,
  mode text,
  timings_2 text,
  timings_3 text,
  date_2 date,
  date_3 date,
  brief_outline text,
  talk_status text,
  onhold_reason text,
  CONSTRAINT tblalumnitalks_pkey PRIMARY KEY (alumniid),
  CONSTRAINT tblalumnitalks_alumniid_fkey FOREIGN KEY (alumniid) REFERENCES public.tbl_alumni(alumniid)
);
CREATE TABLE public.tblcard (
  cardid integer NOT NULL DEFAULT nextval('tblcard_cardid_seq'::regclass),
  alumniid integer NOT NULL,
  cardpicture character varying,
  cardaddress character varying,
  cnicno character varying,
  status character varying,
  createdat timestamp without time zone,
  card_image text,
  printed boolean,
  reason_onhold text,
  validity_date date,
  comment text,
  CONSTRAINT tblcard_pkey PRIMARY KEY (alumniid),
  CONSTRAINT tblcard_alumniid_fkey FOREIGN KEY (alumniid) REFERENCES public.tbl_alumni(alumniid)
);
CREATE TABLE public.tblchapters (
  id integer NOT NULL DEFAULT nextval('tblchapters_id_seq'::regclass),
  chapter_whatsapp text,
  national_chapter text,
  international_chapter text,
  chapter_image text,
  is_active boolean,
  description text,
  cities text,
  CONSTRAINT tblchapters_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tbljobs (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  title text,
  category text,
  company text,
  deadline date,
  location text,
  job_link text,
  CONSTRAINT tbljobs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.tblstories (
  id integer NOT NULL DEFAULT nextval('tblstories_id_seq'::regclass),
  alumniname character varying,
  alumnisession character varying,
  alumnifaculty character varying,
  alumnicompany character varying,
  alumnidesignation character varying,
  alumnicitycountry character varying,
  alumnistories text,
  alumnishortstories character varying,
  alumnistoriesdate date,
  alumniimage1 character varying,
  alumnishowhome character varying,
  CONSTRAINT tblstories_pkey PRIMARY KEY (id),
  CONSTRAINT tblstories_id_fkey FOREIGN KEY (id) REFERENCES public.tbl_alumni(alumniid)
);
CREATE TABLE public.ucoming_events (
  id bigint GENERATED ALWAYS AS IDENTITY NOT NULL,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  category text,
  title text,
  date text,
  chapter_id numeric,
  association_id numeric,
  CONSTRAINT ucoming_events_pkey PRIMARY KEY (id)
);
-- Table: public.user_access_assignments

-- DROP TABLE IF EXISTS public.user_access_assignments;

CREATE TABLE IF NOT EXISTS public.user_access_assignments
(
    id integer NOT NULL DEFAULT nextval('user_access_assignments_id_seq'::regclass),
    userid integer NOT NULL,
    faculty_name text COLLATE pg_catalog."default",
    department_name text COLLATE pg_catalog."default",
    program_name text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    faculty_id bigint,
    department_id bigint,
    program_id bigint,
    CONSTRAINT user_access_assignments_pkey PRIMARY KEY (id),
    CONSTRAINT unique_user_access UNIQUE (userid, faculty_name, department_name, program_name),
    CONSTRAINT fk_access_department FOREIGN KEY (department_id)
        REFERENCES public.tbl_departments (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_access_faculty FOREIGN KEY (faculty_id)
        REFERENCES public.tbl_faculties (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_access_program FOREIGN KEY (program_id)
        REFERENCES public.tbl_programs (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT user_access_assignments_userid_fkey FOREIGN KEY (userid)
        REFERENCES public.tbl_users (userid) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_access_assignments
    OWNER to postgres;
-- Index: idx_user_access_department

-- DROP INDEX IF EXISTS public.idx_user_access_department;

CREATE INDEX IF NOT EXISTS idx_user_access_department
    ON public.user_access_assignments USING btree
    (department_name COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: idx_user_access_faculty

-- DROP INDEX IF EXISTS public.idx_user_access_faculty;

CREATE INDEX IF NOT EXISTS idx_user_access_faculty
    ON public.user_access_assignments USING btree
    (faculty_name COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: idx_user_access_program

-- DROP INDEX IF EXISTS public.idx_user_access_program;

CREATE INDEX IF NOT EXISTS idx_user_access_program
    ON public.user_access_assignments USING btree
    (program_name COLLATE pg_catalog."default" ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Index: idx_user_access_userid

-- DROP INDEX IF EXISTS public.idx_user_access_userid;

CREATE INDEX IF NOT EXISTS idx_user_access_userid
    ON public.user_access_assignments USING btree
    (userid ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

-- Index: idx_user_access_faculty_id

-- DROP INDEX IF EXISTS public.idx_user_access_faculty_id;

CREATE INDEX IF NOT EXISTS idx_user_access_faculty_id
    ON public.user_access_assignments USING btree
    (faculty_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

-- Index: idx_user_access_department_id

-- DROP INDEX IF EXISTS public.idx_user_access_department_id;

CREATE INDEX IF NOT EXISTS idx_user_access_department_id
    ON public.user_access_assignments USING btree
    (department_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;

-- Index: idx_user_access_program_id

-- DROP INDEX IF EXISTS public.idx_user_access_program_id;

CREATE INDEX IF NOT EXISTS idx_user_access_program_id
    ON public.user_access_assignments USING btree
    (program_id ASC NULLS LAST)
    WITH (fillfactor=100, deduplicate_items=True)
    TABLESPACE pg_default;
-- Table: public.distinguished_alumni

-- DROP TABLE IF EXISTS public.distinguished_alumni;

CREATE TABLE IF NOT EXISTS public.distinguished_alumni
(
    id integer NOT NULL DEFAULT nextval('distinguished_alumni_id_seq'::regclass),
    slug character varying(255) COLLATE pg_catalog."default" NOT NULL,
    name character varying(500) COLLATE pg_catalog."default" NOT NULL,
    image character varying(500) COLLATE pg_catalog."default" NOT NULL,
    role text COLLATE pg_catalog."default" NOT NULL,
    summary text COLLATE pg_catalog."default" NOT NULL,
    headline text COLLATE pg_catalog."default",
    quote text COLLATE pg_catalog."default",
    quote_by character varying(255) COLLATE pg_catalog."default",
    tags jsonb DEFAULT '[]'::jsonb,
    stats jsonb DEFAULT '[]'::jsonb,
    achievements jsonb DEFAULT '[]'::jsonb,
    story jsonb NOT NULL DEFAULT '[]'::jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT distinguished_alumni_pkey PRIMARY KEY (id),
    CONSTRAINT distinguished_alumni_slug_key UNIQUE (slug)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.distinguished_alumni
    OWNER to postgres;

    -- Table: public.tbljobs

-- DROP TABLE IF EXISTS public.tbljobs;

CREATE TABLE IF NOT EXISTS public.tbljobs
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    title text COLLATE pg_catalog."default",
    category text COLLATE pg_catalog."default",
    company text COLLATE pg_catalog."default",
    deadline date,
    location text COLLATE pg_catalog."default",
    job_link text COLLATE pg_catalog."default",
    CONSTRAINT tbljobs_pkey PRIMARY KEY (id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.tbljobs
    OWNER to postgres;


    -- Table: public.users

-- DROP TABLE IF EXISTS public.users;

CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL DEFAULT nextval('users_id_seq'::regclass),
    email text COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.users
    OWNER to postgres;

    -- Table: public.roles

-- DROP TABLE IF EXISTS public.roles;

CREATE TABLE IF NOT EXISTS public.roles
(
    id bigint NOT NULL DEFAULT nextval('roles_id_seq'::regclass),
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_name_key UNIQUE (name)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.roles
    OWNER to postgres;

    -- Table: public.permissions

-- DROP TABLE IF EXISTS public.permissions;

CREATE TABLE IF NOT EXISTS public.permissions
(
    id bigint NOT NULL DEFAULT nextval('permissions_id_seq'::regclass),
    action text COLLATE pg_catalog."default" NOT NULL,
    resource text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    CONSTRAINT permissions_pkey PRIMARY KEY (id),
    CONSTRAINT unique_permission UNIQUE (action, resource)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.permissions
    OWNER to postgres;


    -- Table: public.user_roles

-- DROP TABLE IF EXISTS public.user_roles;

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    assigned_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id)
        REFERENCES public.roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_roles
    OWNER to postgres;


    -- Table: public.role_permissions

-- DROP TABLE IF EXISTS public.role_permissions;

CREATE TABLE IF NOT EXISTS public.role_permissions
(
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL,
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id)
        REFERENCES public.permissions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id)
        REFERENCES public.roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.role_permissions
    OWNER to postgres;

    -- Table: public.resources

-- DROP TABLE IF EXISTS public.resources;

CREATE TABLE IF NOT EXISTS public.resources
(
    id bigint NOT NULL DEFAULT nextval('resources_id_seq'::regclass),
    type text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    parent_id bigint,
    CONSTRAINT resources_pkey PRIMARY KEY (id),
    CONSTRAINT fk_resources_parent FOREIGN KEY (parent_id)
        REFERENCES public.resources (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.resources
    OWNER to postgres;

    -- Table: public.user_resource_access

-- DROP TABLE IF EXISTS public.user_resource_access;

CREATE TABLE IF NOT EXISTS public.user_resource_access
(
    id bigint NOT NULL DEFAULT nextval('user_resource_access_id_seq'::regclass),
    user_id bigint NOT NULL,
    resource_id bigint NOT NULL,
    access_level text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_resource_access_pkey PRIMARY KEY (id),
    CONSTRAINT unique_user_resource UNIQUE (user_id, resource_id),
    CONSTRAINT fk_ura_resource FOREIGN KEY (resource_id)
        REFERENCES public.resources (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_ura_user FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT user_resource_access_access_level_check CHECK (access_level = ANY (ARRAY['read'::text, 'write'::text, 'admin'::text]))
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.user_resource_access
    OWNER to postgres;