-- Disable statement timeout just in case
SET statement_timeout = 0;

-- ================================================
-- TABLE: alumni_chapter
-- ================================================

create table public.tblchapters (
  id serial not null,
  chapter_whatsapp text null,
  national_chapter text null,
  international_chapter text null,
  chapter_image text null,
  is_active boolean null,
  description text null,
  constraint tblchapters_pkey primary key (id)
) TABLESPACE pg_default;
-- ================================================
-- TABLE: alumni_memberships
-- ================================================
create table public.alumni_memberships (
  id integer generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  gym_membership_month text null,
  swimmingpool_membership_month text null,
  constraint alumni_memberships_pkey primary key (id),
  constraint alumni_memberships_id_fkey foreign KEY (id) references tbl_alumni (alumniid)
) TABLESPACE pg_default;
-- ================================================
-- TABLE: alumni_scholarships
-- ================================================
create table public.alumni_scholarships (
  id integer generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  kinship_firstname text null,
  kinship_lastname text null,
  kinship_cnic text null,
  apply_for text null,
  degree_title text null,
  constraint alumni_scholarships_pkey primary key (id),
  constraint alumni_scholarships_id_fkey foreign KEY (id) references tbl_alumni (alumniid)
) TABLESPACE pg_default;

-- ================================================
-- TABLE: tbl_alumni  (Main table)
-- ================================================
create table public.tbl_alumni (
  alumniid serial not null,
  alumniemail character varying(150) not null,
  password text null,
  todaydate timestamp without time zone null,
  registrationno character varying(20) null,
  sapid character varying(20) null,
  alumniname character varying(200) null,
  gender character varying(50) null,
  fathername character varying(200) null,
  dateofbirth character varying(50) null,
  maritalstatus character varying(50) null,
  cnicpassport character varying(50) null,
  contactno character varying(50) null,
  contactno1 character varying(50) null,
  contactno1show text null,
  personalemail character varying(100) null,
  personalemailshow text null,
  universityemail character varying(100) null,
  country character varying(50) null,
  province character varying(50) null,
  city character varying(50) null,
  address character varying(250) null,
  academicsession character varying(50) null,
  degreetitle character varying(300) null,
  cgpa double precision null,
  yearofstarting integer null,
  yearofending integer null,
  facultyname character varying(100) null,
  campusname character varying(100) null,
  departmentname character varying(300) null,
  majorsubject character varying(100) null,
  industry character varying(100) null,
  employeed character varying(10) null,
  nameoforganization character varying(100) null,
  designation character varying(100) null,
  totalyearsofexpereince character varying(10) null,
  officialemail character varying(100) null,
  officialnumber character varying(50) null,
  work_city text null,
  supervisordesignation character varying(100) null,
  work_country text null,
  supervisornumber character varying(50) null,
  image1 character varying(200) null,
  cv character varying(200) null,
  aboutme text null,
  lasttimelogin character varying(50) null,
  logincount integer null,
  verify character varying null,
  emailsendcount smallint null,
  emailsendstatus character varying(100) null,
  createddatetime character varying(50) null,
  facebook character varying(300) null,
  instagram character varying(300) null,
  youtube character varying(300) null,
  linkedin character varying(300) null,
  datasource character varying(50) null,
  alumnistatus character varying(50) null,
  higher_education_institute_name text null,
  degree_title text null,
  is_scholarship text null,
  higher_education_program text null,
  father_cnic text null,
  image2 text null,
  association_id bigint null,
  constraint tbl_alumni_pkey primary key (alumniid),
  constraint tbl_alumni_association_id_fkey foreign KEY (association_id) references tbl_associations (id)
) TABLESPACE pg_default;
-- ================================================
-- TABLE: tblchapters
-- ================================================
create table public.tblchapters (
  id serial not null,
  chapter_whatsapp text null,
  national_chapter text null,
  international_chapter text null,
  chapter_image text null,
  is_active boolean null,
  description text null,
  constraint tblchapters_pkey primary key (id)
) TABLESPACE pg_default;

-- ================================================
-- TABLE: tblcard
-- ================================================
create table public.tblcard (
  cardid serial not null,
  alumniid integer not null,
  cardpicture character varying(50) null,
  cardaddress character varying(200) null,
  cnicno character varying(50) null,
  status character varying(50) null,
  createdat timestamp without time zone null,
  card_image text null,
  printed boolean null,
  constraint tblcard_pkey primary key (alumniid),
  constraint tblcard_alumniid_fkey foreign KEY (alumniid) references tbl_alumni (alumniid) on delete CASCADE
) TABLESPACE pg_default;

-- ================================================
-- TABLE: tblalumnitalks
-- ================================================
CREATE TABLE public.tblalumnitalks (
  id SERIAL,
  alumniid INT NOT NULL,
  alumnitalks VARCHAR(10),
  mentorshipprogram VARCHAR(10),
  topic VARCHAR(500),
  day VARCHAR(20),
  timings VARCHAR(20),
  activity VARCHAR(50),
  linkedin VARCHAR(300),
  PRIMARY KEY (alumniid),
  FOREIGN KEY (alumniid) REFERENCES public.tbl_alumni(alumniid) ON DELETE CASCADE
);

-- ================================================
-- TABLE: tblalumnistories
-- ================================================
CREATE TABLE public.tblalumnistories (
  alumniid INT NOT NULL PRIMARY KEY,
  alumnistories TEXT,
  alumniimage VARCHAR(50),
  status VARCHAR(20),
  createdat TIMESTAMP,
  FOREIGN KEY (alumniid) REFERENCES public.tbl_alumni(alumniid) ON DELETE CASCADE
);

-- ================================================
-- TABLE: tblalumniassociation
-- ================================================
CREATE TABLE public.tblalumniassociation (
  id SERIAL,
  alumniid INT NOT NULL,
  q1 VARCHAR(200),
  q2 VARCHAR(300),
  q2others VARCHAR(300),
  q3 VARCHAR(50),
  q4 VARCHAR(300),
  q5 VARCHAR(50),
  q6 VARCHAR(50),
  q7 VARCHAR(1000),
  createddatetime TIMESTAMP,
  PRIMARY KEY (alumniid),
  FOREIGN KEY (alumniid) REFERENCES public.tbl_alumni(alumniid) ON DELETE CASCADE
);

-- ================================================
-- TABLE: tblstories
-- ================================================
CREATE TABLE public.tblstories (
  id SERIAL PRIMARY KEY,
  alumniname VARCHAR(50),
  alumnisession VARCHAR(50),
  alumnifaculty VARCHAR(50),
  alumnicompany VARCHAR(50),
  alumnidesignation VARCHAR(50),
  alumnicitycountry VARCHAR(50),
  alumnistories TEXT,
  alumnishortstories VARCHAR(500),
  alumnistoriesdate DATE,
  alumniimage1 VARCHAR(50),
  alumnishowhome VARCHAR(10)
);

-- ================================================
-- TABLE: tbl_events
-- ================================================
CREATE TABLE public.tbl_events (
  id SERIAL PRIMARY KEY,
  category VARCHAR(100),
  title VARCHAR(200),
  shortdescription VARCHAR(500),
  longdescription TEXT,
  fromdate DATE,
  todate DATE,
  eventtime VARCHAR(50),
  image1 VARCHAR(50) NOT NULL,
  image2 VARCHAR(50),
  image3 VARCHAR(50),
  image4 VARCHAR(50),
  image5 VARCHAR(50)
);

-- ================================================
-- TABLE: tbl_banner
-- ================================================
CREATE TABLE public.tbl_banner (
  bannerid SERIAL PRIMARY KEY,
  bannertitle1 VARCHAR(150),
  bannertitle2 VARCHAR(150),
  bannertitle3 VARCHAR(200),
  bannerimage VARCHAR(100),
  orderby SMALLINT
);

-- ================================================
-- TABLE: tbl_users (Admins / System Users)
-- ================================================
CREATE TABLE public.tbl_users (
  userid SERIAL PRIMARY KEY,
  email VARCHAR(150),
  password VARCHAR(50),
  firstname VARCHAR(100),
  lastname VARCHAR(100),
  department VARCHAR(100),
  type VARCHAR(50),
  blocked BOOLEAN,
  lastlogindatetime VARCHAR(50)
);

-- ================================================
-- TABLE: alumnichapterslocation
-- ================================================
CREATE TABLE public.alumnichapterslocation (
  chapterid SERIAL PRIMARY KEY,
  categoryname VARCHAR(50),
  chaptercode VARCHAR(10),
  chaptertitle VARCHAR(100),
  chapterlocation VARCHAR(200) NOT NULL,
  chapterwhatsapp VARCHAR(300)
);


create table public.tbl_associations (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone not null default now(),
  title text null,
  description text null,
  dean text null,
  dean_message text null,
  phone text null,
  email text null,
  address text null,
  image text null,
  constraint tbl_associations_pkey primary key (id)
) TABLESPACE pg_default;