-- ================================================
-- Migration: Create Standard RBAC Schema
-- Purpose: Set up industry-standard RBAC tables
-- Dependencies: None (creates new tables)
-- Safety: Non-destructive (creates new tables only)
-- ================================================

-- ================================================
-- 1. USERS TABLE (New RBAC User Table)
-- ================================================
-- Note: This is separate from tbl_users (old system)
-- We'll migrate data from tbl_users later

-- Create table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.users
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 
        START 1 
        MINVALUE 1 
        MAXVALUE 9223372036854775807 
        CACHE 1
    ),
    email text COLLATE pg_catalog."default" NOT NULL,
    password_hash text COLLATE pg_catalog."default" NOT NULL,
    is_active boolean NOT NULL DEFAULT true,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    -- Legacy fields for migration mapping
    legacy_userid integer, -- Maps to tbl_users.userid
    legacy_type text, -- Maps to tbl_users.type (for reference)
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_key UNIQUE (email)
)
TABLESPACE pg_default;

-- Add missing columns if table already exists
DO $$
BEGIN
    -- Add legacy_userid column if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'users' 
        AND column_name = 'legacy_userid'
    ) THEN
        ALTER TABLE public.users ADD COLUMN legacy_userid integer;
        RAISE NOTICE 'Added legacy_userid column to users table';
    END IF;

    -- Add legacy_type column if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'users' 
        AND column_name = 'legacy_type'
    ) THEN
        ALTER TABLE public.users ADD COLUMN legacy_type text;
        RAISE NOTICE 'Added legacy_type column to users table';
    END IF;

    -- Add updated_at column if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'users' 
        AND column_name = 'updated_at'
    ) THEN
        ALTER TABLE public.users ADD COLUMN updated_at timestamp with time zone NOT NULL DEFAULT now();
        RAISE NOTICE 'Added updated_at column to users table';
    END IF;
END $$;

-- Add unique constraint on legacy_userid if it doesn't exist and column exists
DO $$
BEGIN
    -- Check if legacy_userid column exists first
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'users' 
        AND column_name = 'legacy_userid'
    ) THEN
        -- Only add constraint if it doesn't exist
        IF NOT EXISTS (
            SELECT 1 FROM information_schema.table_constraints 
            WHERE table_schema = 'public' 
            AND table_name = 'users' 
            AND constraint_name = 'users_legacy_userid_unique'
        ) THEN
            ALTER TABLE public.users ADD CONSTRAINT users_legacy_userid_unique UNIQUE (legacy_userid);
            RAISE NOTICE 'Added unique constraint on legacy_userid';
        END IF;
    END IF;
END $$;

COMMENT ON TABLE public.users IS 'New RBAC user table - replaces tbl_users for RBAC system';

-- Add comments on columns (only if columns exist)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'users' 
        AND column_name = 'legacy_userid'
    ) THEN
        COMMENT ON COLUMN public.users.legacy_userid IS 'Temporary field to map to old tbl_users.userid during migration';
    END IF;
    
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'users' 
        AND column_name = 'legacy_type'
    ) THEN
        COMMENT ON COLUMN public.users.legacy_type IS 'Temporary field to store old role type during migration';
    END IF;
END $$;

-- ================================================
-- 2. ROLES TABLE
-- ================================================

CREATE TABLE IF NOT EXISTS public.roles
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 
        START 1 
        MINVALUE 1 
        MAXVALUE 9223372036854775807 
        CACHE 1
    ),
    name text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT roles_pkey PRIMARY KEY (id),
    CONSTRAINT roles_name_key UNIQUE (name)
)
TABLESPACE pg_default;

COMMENT ON TABLE public.roles IS 'RBAC roles - defines user roles (superadmin, admin, viewer, alumni)';
COMMENT ON COLUMN public.roles.name IS 'Role name (must be unique)';

-- ================================================
-- 3. PERMISSIONS TABLE
-- ================================================

CREATE TABLE IF NOT EXISTS public.permissions
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 
        START 1 
        MINVALUE 1 
        MAXVALUE 9223372036854775807 
        CACHE 1
    ),
    action text COLLATE pg_catalog."default" NOT NULL,
    resource text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT permissions_pkey PRIMARY KEY (id),
    CONSTRAINT unique_permission UNIQUE (action, resource)
)
TABLESPACE pg_default;

COMMENT ON TABLE public.permissions IS 'RBAC permissions - defines actions on resources';
COMMENT ON COLUMN public.permissions.action IS 'Action: read, write, delete, manage_users, etc.';
COMMENT ON COLUMN public.permissions.resource IS 'Resource: alumni, events, users, chapters, etc.';

-- ================================================
-- 4. USER_ROLES TABLE (Many-to-Many)
-- ================================================

CREATE TABLE IF NOT EXISTS public.user_roles
(
    user_id bigint NOT NULL,
    role_id bigint NOT NULL,
    assigned_at timestamp with time zone NOT NULL DEFAULT now(),
    assigned_by bigint, -- User who assigned this role
    CONSTRAINT user_roles_pkey PRIMARY KEY (user_id, role_id),
    CONSTRAINT fk_user_roles_role FOREIGN KEY (role_id)
        REFERENCES public.roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_user FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_user_roles_assigned_by FOREIGN KEY (assigned_by)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE SET NULL
)
TABLESPACE pg_default;

COMMENT ON TABLE public.user_roles IS 'User-to-role assignments (many-to-many)';

-- Add missing columns if table already exists
DO $$
BEGIN
    -- Add assigned_by column if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'user_roles' 
        AND column_name = 'assigned_by'
    ) THEN
        ALTER TABLE public.user_roles ADD COLUMN assigned_by bigint;
        RAISE NOTICE 'Added assigned_by column to user_roles table';
    END IF;
END $$;

-- Add comment on assigned_by column (only if column exists)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'user_roles' 
        AND column_name = 'assigned_by'
    ) THEN
        COMMENT ON COLUMN public.user_roles.assigned_by IS 'User who assigned this role (audit trail)';
    END IF;
END $$;

-- Add missing foreign key constraint if it doesn't exist
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE table_schema = 'public' 
        AND table_name = 'user_roles' 
        AND constraint_name = 'fk_user_roles_assigned_by'
    ) THEN
        ALTER TABLE public.user_roles 
        ADD CONSTRAINT fk_user_roles_assigned_by FOREIGN KEY (assigned_by)
            REFERENCES public.users (id) MATCH SIMPLE
            ON UPDATE NO ACTION
            ON DELETE SET NULL;
        RAISE NOTICE 'Added fk_user_roles_assigned_by foreign key constraint';
    END IF;
END $$;

-- ================================================
-- 5. ROLE_PERMISSIONS TABLE (Many-to-Many)
-- ================================================

CREATE TABLE IF NOT EXISTS public.role_permissions
(
    role_id bigint NOT NULL,
    permission_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT role_permissions_pkey PRIMARY KEY (role_id, permission_id),
    CONSTRAINT fk_role_permissions_permission FOREIGN KEY (permission_id)
        REFERENCES public.permissions (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_role_permissions_role FOREIGN KEY (role_id)
        REFERENCES public.roles (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE
)
TABLESPACE pg_default;

COMMENT ON TABLE public.role_permissions IS 'Role-to-permission mappings (many-to-many)';

-- ================================================
-- 6. RESOURCES TABLE (Hierarchical)
-- ================================================
-- Represents organizational structure: faculties → departments → programs

CREATE TABLE IF NOT EXISTS public.resources
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 
        START 1 
        MINVALUE 1 
        MAXVALUE 9223372036854775807 
        CACHE 1
    ),
    type text COLLATE pg_catalog."default" NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    parent_id bigint,
    -- Legacy mapping fields
    legacy_faculty_id bigint, -- Maps to tbl_faculties.id
    legacy_department_id bigint, -- Maps to tbl_departments.id
    legacy_program_id bigint, -- Maps to tbl_programs.id
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT resources_pkey PRIMARY KEY (id),
    CONSTRAINT fk_resources_parent FOREIGN KEY (parent_id)
        REFERENCES public.resources (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT resources_type_check CHECK (
        type IN ('faculty', 'department', 'program', 'chapter', 'association', 'event', 'alumni')
    ),
    CONSTRAINT resources_unique_name_parent UNIQUE (type, name, parent_id)
)
TABLESPACE pg_default;

-- Add missing columns if table already exists
DO $$
BEGIN
    -- Add legacy_faculty_id column if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'resources' 
        AND column_name = 'legacy_faculty_id'
    ) THEN
        ALTER TABLE public.resources ADD COLUMN legacy_faculty_id bigint;
        RAISE NOTICE 'Added legacy_faculty_id column to resources table';
    END IF;

    -- Add legacy_department_id column if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'resources' 
        AND column_name = 'legacy_department_id'
    ) THEN
        ALTER TABLE public.resources ADD COLUMN legacy_department_id bigint;
        RAISE NOTICE 'Added legacy_department_id column to resources table';
    END IF;

    -- Add legacy_program_id column if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'resources' 
        AND column_name = 'legacy_program_id'
    ) THEN
        ALTER TABLE public.resources ADD COLUMN legacy_program_id bigint;
        RAISE NOTICE 'Added legacy_program_id column to resources table';
    END IF;

    -- Add updated_at column if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'resources' 
        AND column_name = 'updated_at'
    ) THEN
        ALTER TABLE public.resources ADD COLUMN updated_at timestamp with time zone NOT NULL DEFAULT now();
        RAISE NOTICE 'Added updated_at column to resources table';
    END IF;
END $$;

-- Add missing constraints if table already exists
DO $$
BEGIN
    -- Add type check constraint if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE table_schema = 'public' 
        AND table_name = 'resources' 
        AND constraint_name = 'resources_type_check'
    ) THEN
        ALTER TABLE public.resources ADD CONSTRAINT resources_type_check CHECK (
            type IN ('faculty', 'department', 'program', 'chapter', 'association', 'event', 'alumni')
        );
        RAISE NOTICE 'Added resources_type_check constraint';
    END IF;

    -- Add unique constraint if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.table_constraints 
        WHERE table_schema = 'public' 
        AND table_name = 'resources' 
        AND constraint_name = 'resources_unique_name_parent'
    ) THEN
        ALTER TABLE public.resources ADD CONSTRAINT resources_unique_name_parent UNIQUE (type, name, parent_id);
        RAISE NOTICE 'Added resources_unique_name_parent constraint';
    END IF;
END $$;

COMMENT ON TABLE public.resources IS 'Hierarchical resource tree - represents organizational structure and entities';
COMMENT ON COLUMN public.resources.type IS 'Resource type: faculty, department, program, etc.';
COMMENT ON COLUMN public.resources.name IS 'Resource name';
COMMENT ON COLUMN public.resources.parent_id IS 'Parent resource (for hierarchy: department.parent = faculty)';

-- Add comments on legacy columns (only if columns exist)
DO $$
BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'resources' 
        AND column_name = 'legacy_faculty_id'
    ) THEN
        COMMENT ON COLUMN public.resources.legacy_faculty_id IS 'Temporary mapping to tbl_faculties.id during migration';
    END IF;
    
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'resources' 
        AND column_name = 'legacy_department_id'
    ) THEN
        COMMENT ON COLUMN public.resources.legacy_department_id IS 'Temporary mapping to tbl_departments.id during migration';
    END IF;
    
    IF EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'resources' 
        AND column_name = 'legacy_program_id'
    ) THEN
        COMMENT ON COLUMN public.resources.legacy_program_id IS 'Temporary mapping to tbl_programs.id during migration';
    END IF;
END $$;

-- ================================================
-- 7. USER_RESOURCE_ACCESS TABLE
-- ================================================
-- Defines user access to specific resources with access levels

CREATE TABLE IF NOT EXISTS public.user_resource_access
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        INCREMENT 1 
        START 1 
        MINVALUE 1 
        MAXVALUE 9223372036854775807 
        CACHE 1
    ),
    user_id bigint NOT NULL,
    resource_id bigint NOT NULL,
    access_level text COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_resource_access_pkey PRIMARY KEY (id),
    CONSTRAINT unique_user_resource UNIQUE (user_id, resource_id),
    CONSTRAINT fk_ura_resource FOREIGN KEY (resource_id)
        REFERENCES public.resources (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT fk_ura_user FOREIGN KEY (user_id)
        REFERENCES public.users (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE CASCADE,
    CONSTRAINT user_resource_access_access_level_check CHECK (
        access_level = ANY (ARRAY['read'::text, 'write'::text, 'admin'::text])
    )
)
TABLESPACE pg_default;

COMMENT ON TABLE public.user_resource_access IS 'User-to-resource access assignments with access levels';
COMMENT ON COLUMN public.user_resource_access.access_level IS 'Access level: read (viewer), write (admin), admin (full control)';

-- Add missing columns if table already exists
DO $$
BEGIN
    -- Add updated_at column if it doesn't exist
    IF NOT EXISTS (
        SELECT 1 FROM information_schema.columns 
        WHERE table_schema = 'public' 
        AND table_name = 'user_resource_access' 
        AND column_name = 'updated_at'
    ) THEN
        ALTER TABLE public.user_resource_access ADD COLUMN updated_at timestamp with time zone NOT NULL DEFAULT now();
        RAISE NOTICE 'Added updated_at column to user_resource_access table';
    END IF;
END $$;

-- ================================================
-- 8. INDEXES FOR PERFORMANCE
-- ================================================

-- Users indexes
CREATE INDEX IF NOT EXISTS idx_users_email 
    ON public.users USING btree (email COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_users_legacy_userid 
    ON public.users USING btree (legacy_userid ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_users_is_active 
    ON public.users USING btree (is_active ASC NULLS LAST)
    TABLESPACE pg_default;

-- Roles indexes
CREATE INDEX IF NOT EXISTS idx_roles_name 
    ON public.roles USING btree (name COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Permissions indexes
CREATE INDEX IF NOT EXISTS idx_permissions_action 
    ON public.permissions USING btree (action COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_permissions_resource 
    ON public.permissions USING btree (resource COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

-- User roles indexes
CREATE INDEX IF NOT EXISTS idx_user_roles_user_id 
    ON public.user_roles USING btree (user_id ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_user_roles_role_id 
    ON public.user_roles USING btree (role_id ASC NULLS LAST)
    TABLESPACE pg_default;

-- Role permissions indexes
CREATE INDEX IF NOT EXISTS idx_role_permissions_role_id 
    ON public.role_permissions USING btree (role_id ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_role_permissions_permission_id 
    ON public.role_permissions USING btree (permission_id ASC NULLS LAST)
    TABLESPACE pg_default;

-- Resources indexes
CREATE INDEX IF NOT EXISTS idx_resources_type 
    ON public.resources USING btree (type COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_resources_parent_id 
    ON public.resources USING btree (parent_id ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_resources_legacy_faculty_id 
    ON public.resources USING btree (legacy_faculty_id ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_resources_legacy_department_id 
    ON public.resources USING btree (legacy_department_id ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_resources_legacy_program_id 
    ON public.resources USING btree (legacy_program_id ASC NULLS LAST)
    TABLESPACE pg_default;

-- User resource access indexes
CREATE INDEX IF NOT EXISTS idx_user_resource_access_user_id 
    ON public.user_resource_access USING btree (user_id ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_user_resource_access_resource_id 
    ON public.user_resource_access USING btree (resource_id ASC NULLS LAST)
    TABLESPACE pg_default;

CREATE INDEX IF NOT EXISTS idx_user_resource_access_access_level 
    ON public.user_resource_access USING btree (access_level COLLATE pg_catalog."default" ASC NULLS LAST)
    TABLESPACE pg_default;

-- Composite index for common queries
CREATE INDEX IF NOT EXISTS idx_user_resource_access_user_resource 
    ON public.user_resource_access USING btree (user_id ASC NULLS LAST, resource_id ASC NULLS LAST)
    TABLESPACE pg_default;

-- ================================================
-- 9. TRIGGERS FOR AUTOMATIC UPDATES
-- ================================================

-- Function to update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Trigger for users
DROP TRIGGER IF EXISTS update_users_updated_at ON public.users;
CREATE TRIGGER update_users_updated_at
    BEFORE UPDATE ON public.users
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- Trigger for resources
DROP TRIGGER IF EXISTS update_resources_updated_at ON public.resources;
CREATE TRIGGER update_resources_updated_at
    BEFORE UPDATE ON public.resources
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- Trigger for user_resource_access
DROP TRIGGER IF EXISTS update_user_resource_access_updated_at ON public.user_resource_access;
CREATE TRIGGER update_user_resource_access_updated_at
    BEFORE UPDATE ON public.user_resource_access
    FOR EACH ROW
    EXECUTE FUNCTION public.update_updated_at_column();

-- ================================================
-- 10. HELPER VIEWS
-- ================================================

-- View: User Roles Summary
CREATE OR REPLACE VIEW public.vw_user_roles_summary AS
SELECT 
    u.id as user_id,
    u.email,
    u.is_active,
    STRING_AGG(r.name, ', ' ORDER BY r.name) as roles,
    COUNT(DISTINCT ur.role_id) as role_count
FROM public.users u
LEFT JOIN public.user_roles ur ON u.id = ur.user_id
LEFT JOIN public.roles r ON ur.role_id = r.id
GROUP BY u.id, u.email, u.is_active;

COMMENT ON VIEW public.vw_user_roles_summary IS 'Summary view showing users and their assigned roles';

-- View: Role Permissions Detail
CREATE OR REPLACE VIEW public.vw_role_permissions_detail AS
SELECT 
    r.id as role_id,
    r.name as role_name,
    r.description as role_description,
    STRING_AGG(p.action || ':' || p.resource, ', ' ORDER BY p.resource, p.action) as permissions,
    COUNT(DISTINCT rp.permission_id) as permission_count
FROM public.roles r
LEFT JOIN public.role_permissions rp ON r.id = rp.role_id
LEFT JOIN public.permissions p ON rp.permission_id = p.id
GROUP BY r.id, r.name, r.description;

COMMENT ON VIEW public.vw_role_permissions_detail IS 'Detailed view showing roles and their permissions';

-- View: User Resource Access Detail
CREATE OR REPLACE VIEW public.vw_user_resource_access_detail AS
SELECT 
    u.id as user_id,
    u.email,
    res.id as resource_id,
    res.type as resource_type,
    res.name as resource_name,
    res.parent_id as resource_parent_id,
    ura.access_level,
    ura.created_at as access_granted_at
FROM public.users u
INNER JOIN public.user_resource_access ura ON u.id = ura.user_id
INNER JOIN public.resources res ON ura.resource_id = res.id
ORDER BY u.email, res.type, res.name;

COMMENT ON VIEW public.vw_user_resource_access_detail IS 'Detailed view showing user access to specific resources';

-- ================================================
-- 11. GRANT PERMISSIONS
-- ================================================

ALTER TABLE public.users OWNER TO postgres;
ALTER TABLE public.roles OWNER TO postgres;
ALTER TABLE public.permissions OWNER TO postgres;
ALTER TABLE public.user_roles OWNER TO postgres;
ALTER TABLE public.role_permissions OWNER TO postgres;
ALTER TABLE public.resources OWNER TO postgres;
ALTER TABLE public.user_resource_access OWNER TO postgres;

-- ================================================
-- END OF SCHEMA CREATION
-- ================================================

-- Verification: Check all tables were created
DO $$
DECLARE
    table_count integer;
BEGIN
    SELECT COUNT(*) INTO table_count
    FROM information_schema.tables
    WHERE table_schema = 'public'
      AND table_name IN ('users', 'roles', 'permissions', 'user_roles', 'role_permissions', 'resources', 'user_resource_access');
    
    IF table_count = 7 THEN
        RAISE NOTICE '✅ All 7 RBAC tables created successfully';
    ELSE
        RAISE WARNING '⚠️ Expected 7 tables, found %', table_count;
    END IF;
END $$;
