-- Scholarship discount categories and CGPA-based tiers (admin Setup → Scholarships).
-- Safe to run multiple times (IF NOT EXISTS).

CREATE TABLE IF NOT EXISTS public.scholarship_discount_categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug text NOT NULL,
  label text NOT NULL,
  flow_type text NOT NULL CHECK (flow_type IN ('fee_discount', 'kinship')),
  default_apply_for text,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT scholarship_discount_categories_slug_unique UNIQUE (slug)
);

CREATE TABLE IF NOT EXISTS public.scholarship_cgpa_discount_tiers (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id integer NOT NULL REFERENCES public.scholarship_discount_categories(id) ON DELETE CASCADE,
  cgpa_min numeric(3, 2) NOT NULL,
  cgpa_max numeric(3, 2) NOT NULL,
  discount_percent numeric(5, 2) NOT NULL,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT scholarship_cgpa_tiers_bounds_chk CHECK (cgpa_min >= 0 AND cgpa_max <= 4 AND cgpa_min <= cgpa_max),
  CONSTRAINT scholarship_cgpa_tiers_percent_chk CHECK (discount_percent >= 0 AND discount_percent <= 100)
);

CREATE INDEX IF NOT EXISTS idx_scholarship_cgpa_tiers_category_id
  ON public.scholarship_cgpa_discount_tiers(category_id);

ALTER TABLE public.alumni_scholarships
  ADD COLUMN IF NOT EXISTS applied_discount_percent numeric(5, 2);

COMMENT ON COLUMN public.alumni_scholarships.applied_discount_percent IS
  'Discount percent resolved from profile CGPA and category tiers at application submit time.';

-- Seed default categories (idempotent on slug)
INSERT INTO public.scholarship_discount_categories (slug, label, flow_type, default_apply_for, sort_order, is_active)
VALUES
  ('admission-fee-masters-75', 'Admission Fee Masters 75%', 'fee_discount', 'Masters', 1, true),
  ('admission-fee-phd-75', 'Admission Fee PhD 75%', 'fee_discount', 'PhD', 2, true),
  ('kinship-15', 'Kinship Tution Discount 15%', 'kinship', NULL, 3, true),
  ('tuition-fee-masters-25', 'Tuition Fee Masters 50%', 'fee_discount', 'Masters', 4, true),
  ('tuition-fee-phd-25', 'Tuition Fee PhD 25%', 'fee_discount', 'PhD', 5, true)
ON CONFLICT (slug) DO NOTHING;

-- Seed default tiers 0.0–4.0 per category (idempotent: only if category has no tiers)
INSERT INTO public.scholarship_cgpa_discount_tiers (category_id, cgpa_min, cgpa_max, discount_percent, sort_order)
SELECT c.id, 0.0, 4.0, v.discount_percent, 0
FROM public.scholarship_discount_categories c
JOIN (VALUES
  ('admission-fee-masters-75', 75.0),
  ('admission-fee-phd-75', 75.0),
  ('kinship-15', 15.0),
  ('tuition-fee-masters-25', 50.0),
  ('tuition-fee-phd-25', 25.0)
) AS v(slug, discount_percent) ON v.slug = c.slug
WHERE NOT EXISTS (
  SELECT 1 FROM public.scholarship_cgpa_discount_tiers t WHERE t.category_id = c.id
);
