-- =====================================================
-- SQL Script to Insert Faculties, Departments, and Programs
-- Generated from PGM_Master_Data_Structured.csv
-- Generated on: 2026-01-02T05:01:29.885Z
-- =====================================================

-- STEP 1: Insert Faculties
INSERT INTO public.tbl_faculties (faculty_name)
VALUES
  ('Faculty of Allied Health Sciences'),
  ('Faculty of Arts & Architecture'),
  ('Faculty of CS & IT'),
  ('Faculty of Engineering'),
  ('Faculty of Language & Literature'),
  ('Faculty of Law'),
  ('Faculty of Management Sciences'),
  ('Faculty of Medicine & Dentistry'),
  ('Faculty of Natural Sciences'),
  ('Faculty of Pharmacy'),
  ('Faculty of Social Sciences'),
  ('International Programs')
ON CONFLICT DO NOTHING;


-- STEP 2: Insert Departments with their Faculty IDs
WITH faculty_ids AS (
  SELECT id, faculty_name FROM public.tbl_faculties
)
INSERT INTO public.tbl_departments (department_name, faculty_id, department_code)
SELECT DISTINCT
  dept.department_name,
  f.id as faculty_id,
  dept.department_code
FROM (VALUES
    ('International Programs', '112702', 'Academy of International Certifications'),
    ('International Programs', '112701', 'Academy of International Qualifications'),
    ('International Programs', '111603', 'Academy of Languages & Professional Dev.'),
    ('International Programs', 'Elumni', 'Elumni'),
    ('International Programs', '11250201', 'PM Kamyab Nojawan Program'),
    ('International Programs', '111502', 'Postgraduate Institute of Law'),
    ('International Programs', '112703', 'UOL - CSUN'),
    ('Faculty of Allied Health Sciences', '111904', 'Center for Research in Molecular Medicin'),
    ('Faculty of Allied Health Sciences', '112214', 'Department of Audiology'),
    ('Faculty of Allied Health Sciences', '112209', 'Department of Optometry & Vision Science'),
    ('Faculty of Allied Health Sciences', '112211', 'Department of Rehabilitation Sciences'),
    ('Faculty of Allied Health Sciences', '112203', 'Department of Sports Sciences'),
    ('Faculty of Allied Health Sciences', '112201', 'Dept of Health Professional Technologies'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT'),
    ('Faculty of Allied Health Sciences', '112212', 'Deptt. of Emerging Allied Health Tech.'),
    ('Faculty of Allied Health Sciences', '113002', 'Lahore Institue of Future Education'),
    ('Faculty of Allied Health Sciences', '112204', 'Lahore School of Nursing'),
    ('Faculty of Allied Health Sciences', '113005', 'NHNC'),
    ('Faculty of Allied Health Sciences', '112210', 'Uni. Inst. of Food Science & Technology'),
    ('Faculty of Allied Health Sciences', '112202', 'University Inst of Diet & Nutri Sciences'),
    ('Faculty of Allied Health Sciences', '112205', 'University Institute of Medical Lab Tech'),
    ('Faculty of Allied Health Sciences', '112207', 'University Institute of Physical Therapy'),
    ('Faculty of Allied Health Sciences', '112208', 'University Institute of Public Health'),
    ('Faculty of Natural Sciences', '111905', 'Department of Chemistry'),
    ('Faculty of Natural Sciences', '111906', 'Department of Environmental Sciences'),
    ('Faculty of Natural Sciences', '111901', 'Department of Mathematics and Statistics'),
    ('Faculty of Natural Sciences', '111902', 'Department of Physics'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech'),
    ('Faculty of Natural Sciences', '111907', 'School of Pain & Regenrative Medicine'),
    ('Faculty of Engineering', '111802', 'Department of Civil Engineering'),
    ('Faculty of Engineering', '111806', 'Department of Computer Engineering'),
    ('Faculty of Engineering', '111801', 'Department of Electrical Engineering'),
    ('Faculty of Engineering', '111803', 'Department of Mechanical Engineering'),
    ('Faculty of Engineering', '111804', 'Department of Technology'),
    ('Faculty of Engineering', '111805', 'Deptt of Electronics & Electrical System'),
    ('Faculty of CS & IT', '112001', 'Department of Computer Sciences & IT'),
    ('Faculty of CS & IT', '112003', 'Department of Intelligent Systems'),
    ('Faculty of CS & IT', '112002', 'Department of Software Engineering'),
    ('Faculty of Social Sciences', '111708', 'Department of Criminology'),
    ('Faculty of Social Sciences', '111702', 'Department of Education'),
    ('Faculty of Social Sciences', '111703', 'Department of Islamic Studies'),
    ('Faculty of Social Sciences', '111707', 'Department of Sociology'),
    ('Faculty of Social Sciences', '111305', 'Lahore School of Behavioural Sciences'),
    ('Faculty of Social Sciences', '111705', 'School of Integrated Social Science'),
    ('Faculty of Management Sciences', '111701', 'Department of Economics'),
    ('Faculty of Management Sciences', '111303', 'Department of Information Management'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School'),
    ('Faculty of Management Sciences', '111302', 'Lahore School of Aviation'),
    ('Faculty of Management Sciences', '113001', 'School of Accountancy & Finance'),
    ('Faculty of Medicine & Dentistry', '112103', 'Department of Medical Education'),
    ('Faculty of Medicine & Dentistry', '112104', 'Heath Professional Develoment & Lifelong'),
    ('Faculty of Medicine & Dentistry', '112102', 'University College of Dentistry'),
    ('Faculty of Medicine & Dentistry', '112101', 'University College of Medicine'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy'),
    ('Faculty of Language & Literature', '111602', 'Department of Urdu'),
    ('Faculty of Language & Literature', '111601', 'Dept of English Language and Literature'),
    ('Faculty of Law', '111501', 'M.A Raoof College of Law'),
    ('Faculty of Arts & Architecture', '111401', 'School of Architecture'),
    ('Faculty of Arts & Architecture', '111402', 'School of Creative Arts'),
    ('Faculty of Arts & Architecture', '111406', 'School of Fashion and Textile')
) AS dept(faculty_name, department_code, department_name)
INNER JOIN faculty_ids f ON f.faculty_name = dept.faculty_name
ON CONFLICT ON CONSTRAINT uniq_department_faculty DO NOTHING;


-- STEP 3: Insert Programs with their Department IDs
WITH department_ids AS (
  SELECT d.id, d.department_name, d.department_code, f.faculty_name
  FROM public.tbl_departments d
  INNER JOIN public.tbl_faculties f ON f.id = d.faculty_id
)
INSERT INTO public.tbl_programs (program_name, department_id, program_abv)
SELECT
  prog.program_name,
  d.id as department_id,
  prog.program_abv
FROM (VALUES
    ('International Programs', '112702', 'Academy of International Certifications', 'Business Formation Certificate - Pre Incubation Plan', 'BFCP-LHR'),
    ('International Programs', '112702', 'Academy of International Certifications', 'Certificate in Business Formation/Entrepreneurship', 'CBF-LHR'),
    ('International Programs', '112702', 'Academy of International Certifications', 'ISO 14001:2015 IRCA EMS Lead Auditor Training', 'ISO-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'ADP in Health and Social Care (Level 4 & 5)', 'ADPHSC-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'ADP in Hospitality Management (Level 4 & 5)', 'ADPHM-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'ADP in Social and Community Work (Level 4 & 5)', 'ADPSCW-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'B.Sc(Hons)Artifical Intelligence', 'BSBAAIQ-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'B.Sc(Hons)Bussiness Management', 'BSBMIQ-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'B.Sc(Hons)Bussiness Management(Top Up Level-6)', 'BSBMITQ-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'B.Sc(Hons)Computer Science', 'BSCSIQ-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'B.Sc(Hons)Computer Science(Top Up Level-6)', 'BSCSTIQ-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'B.Sc(Hons)Cyber Security', 'BSCBSIQ-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'B.Sc(Hons)Health and Social Care', 'BSHSIQ-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'B.Sc(Hons)Health and Social Care(Top Level-6)', 'BSHSTIQ-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'B.Sc(Hons)International Hospitality Management', 'BSHMIQ-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'B.Sc(Hons)International Hospitality Management(Top Level-6)', 'BSHMTIQ-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'B.Sc(Hons)Nursing', 'BSNIQ-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'B.Sc(Hons)Physical Therapy', 'BSPTIQ-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'B.Sc(Hons)Psychology', 'BSPYIQ-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'HNC Arts and Design', 'HNCAD-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'HNC Business( Level 4)', 'HNCBU-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'HNC Computing(Level 4)', 'HNCC-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'HNC Health and Social Care(Level 4)', 'HNCHSC-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'HNC Hospitality Management(Level 4)', 'HNCHM-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'HNC Social and Community Work(Level 4)', 'HNCSCW-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'HND Arts and Design', 'HNDAD-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'HND Business', 'HNDBU-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'HND Computing', 'HNDC-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'HND Health and Social Care', 'HNDHSC-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'HND Hospitality Management', 'HNDHM-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'HND Social and Community Work', 'HNDSCW-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'International Certificate in Health & Social Care', 'ICHSC-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'International Certificate in Hospitality', 'ICH-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'International Certificate in Information Technology', 'ICIT-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'LLB(Hons)', 'LLBIQ-LHR'),
    ('International Programs', '112701', 'Academy of International Qualifications', 'Pre-Sessional Program', 'PHPIQ-LHR'),
    ('International Programs', '111603', 'Academy of Languages & Professional Dev.', 'Arabic - Beginner Level', 'ALCB-LHR'),
    ('International Programs', '111603', 'Academy of Languages & Professional Dev.', 'Arabic - Intermediate Level', 'ALCI-LHR'),
    ('International Programs', '111603', 'Academy of Languages & Professional Dev.', 'Arabic Language Course', 'ALC-LHR'),
    ('International Programs', '111603', 'Academy of Languages & Professional Dev.', 'German - A1 Level', 'GLCA1-LHR'),
    ('International Programs', '111603', 'Academy of Languages & Professional Dev.', 'German - A2 Level', 'GLCA2-LHR'),
    ('International Programs', '111603', 'Academy of Languages & Professional Dev.', 'German Language Course', 'GLC-LHR'),
    ('International Programs', '111603', 'Academy of Languages & Professional Dev.', 'Japanese Language Course', 'JLC-LHR'),
    ('International Programs', '111603', 'Academy of Languages & Professional Dev.', 'Persian-Beginner Level', 'PLCB-LHR'),
    ('International Programs', 'Elumni', 'Elumni', 'Back-End Web Development', 'BEWD-LHR'),
    ('International Programs', 'Elumni', 'Elumni', 'Cloud Computing and Devops', 'CCD-LHR'),
    ('International Programs', 'Elumni', 'Elumni', 'Front-End Web Development', 'FEWD-LHR'),
    ('International Programs', 'Elumni', 'Elumni', 'Full Stack Capstone Project', 'FSCP-LHR'),
    ('International Programs', 'Elumni', 'Elumni', 'Full Stack Web Development', 'FSWD-LHR'),
    ('International Programs', '11250201', 'PM Kamyab Nojawan Program', 'AutoCad Mechanical', 'ACM-LHR'),
    ('International Programs', '11250201', 'PM Kamyab Nojawan Program', 'PM Kamyab Nijawan Program', 'CIT-LHR'),
    ('International Programs', '11250201', 'PM Kamyab Nojawan Program', 'SAP - ERP', 'SAP-LHR'),
    ('International Programs', '111502', 'Postgraduate Institute of Law', 'Master of Laws', 'LLM-LHR'),
    ('International Programs', '112703', 'UOL - CSUN', 'BS Business Administration(Finance)-CSUN', 'BSBA-CSN-LHR'),
    ('International Programs', '112703', 'UOL - CSUN', 'BS Computer Science - CSUN', 'BSCS-CSN-LHR'),
    ('Faculty of Allied Health Sciences', '111904', 'Center for Research in Molecular Medicin', 'Diploma in Medical Radiology (Diagnostic)', 'DMRD-LHR'),
    ('Faculty of Allied Health Sciences', '112214', 'Department of Audiology', 'Bachelor of Science in Audiology', 'BSA-LHR'),
    ('Faculty of Allied Health Sciences', '112209', 'Department of Optometry & Vision Science', 'Bachelor of Vision Sciences', 'BVS-LHR'),
    ('Faculty of Allied Health Sciences', '112209', 'Department of Optometry & Vision Science', 'Doctor of Optometry', 'OD-LHR'),
    ('Faculty of Allied Health Sciences', '112209', 'Department of Optometry & Vision Science', 'Post Professional Doctor of Optometry', 'POD-LHR'),
    ('Faculty of Allied Health Sciences', '112209', 'Department of Optometry & Vision Science', 'Post Professional Doctor of Optometry', 'PPDO-LHR'),
    ('Faculty of Allied Health Sciences', '112209', 'Department of Optometry & Vision Science', 'Transitional Doctor of Optometry', 'TOD-LHR'),
    ('Faculty of Allied Health Sciences', '112209', 'Department of Optometry & Vision Science', 'Transitional Doctor of Optometry', 'TDO-LHR'),
    ('Faculty of Allied Health Sciences', '112211', 'Department of Rehabilitation Sciences', 'Bachelor of Science in Occupational Therapy', 'BSOT-LHR'),
    ('Faculty of Allied Health Sciences', '112211', 'Department of Rehabilitation Sciences', 'Bachelor of Science in Orthotics and Prosthetic Technology', 'BSORPT-LHR'),
    ('Faculty of Allied Health Sciences', '112211', 'Department of Rehabilitation Sciences', 'Bachelor of Science in Rehabilitation Sciences', 'BSRS-LHR'),
    ('Faculty of Allied Health Sciences', '112211', 'Department of Rehabilitation Sciences', 'Bachelor of Science in Speech and Language Pathology', 'BSSLP-LHR'),
    ('Faculty of Allied Health Sciences', '112211', 'Department of Rehabilitation Sciences', 'Master of Science in Speech Language Pathology / Hearing Sciences (Audiology)', 'MSSLHS-LHR'),
    ('Faculty of Allied Health Sciences', '112211', 'Department of Rehabilitation Sciences', 'Post Graduate Diploma in Clinical Speech Language Pathology Autism Spectrum Disorders', 'PGDAS-LHR'),
    ('Faculty of Allied Health Sciences', '112211', 'Department of Rehabilitation Sciences', 'Post Graduate Diploma in Clinical Speech Language Pathology Dysphagiaate Diploma in Clinical Speech Language Pathology Dysphagia', 'PGDD-LHR'),
    ('Faculty of Allied Health Sciences', '112211', 'Department of Rehabilitation Sciences', 'Post Graduate Diploma in Clinical Speech Language Pathology Aphasia', 'PGDA-LHR'),
    ('Faculty of Allied Health Sciences', '112203', 'Department of Sports Sciences', 'Bachelor of Science in Sports Sciences and Physical Education', 'BSSPE-LHR'),
    ('Faculty of Allied Health Sciences', '112203', 'Department of Sports Sciences', 'Bachelor of Studies in Physical Education(Sports Sciences)', 'BSPE-LHR'),
    ('Faculty of Allied Health Sciences', '112203', 'Department of Sports Sciences', 'Doctor of Philosophy in Sports Science and Physical Education', 'DSSPE-LHR'),
    ('Faculty of Allied Health Sciences', '112203', 'Department of Sports Sciences', 'Doctor of Philosophy in Sports Science', 'DSS-LHR'),
    ('Faculty of Allied Health Sciences', '112203', 'Department of Sports Sciences', 'Master of Philosophy in Sports Sciences and Physical Education', 'PSSPE-LHR'),
    ('Faculty of Allied Health Sciences', '112203', 'Department of Sports Sciences', 'Master of Science in Sports Medicine', 'MSSM-LHR'),
    ('Faculty of Allied Health Sciences', '112203', 'Department of Sports Sciences', 'Master of Science in Sports and Exercise Psychology', 'SPPSY-LHR'),
    ('Faculty of Allied Health Sciences', '112203', 'Department of Sports Sciences', 'Master of Sports Sciences and Physical Education', 'MSSPE-LHR'),
    ('Faculty of Allied Health Sciences', '112201', 'Dept of Health Professional Technologies', 'Bachelor of Science in Anesthesia Technology', 'BSAT-LHR'),
    ('Faculty of Allied Health Sciences', '112201', 'Dept of Health Professional Technologies', 'Bachelor of Science in Critical Care Technorogy', 'BSCCT-LHR'),
    ('Faculty of Allied Health Sciences', '112201', 'Dept of Health Professional Technologies', 'Bachelor of Science in Emergency Technology', 'BSEMT-LHR'),
    ('Faculty of Allied Health Sciences', '112201', 'Dept of Health Professional Technologies', 'Bachelor of Science in Emergency and Intensive Care Technology', 'BSEICT-LHR'),
    ('Faculty of Allied Health Sciences', '112201', 'Dept of Health Professional Technologies', 'Bachelor of Science in Intensive Care Technology', 'BSICT-LHR'),
    ('Faculty of Allied Health Sciences', '112201', 'Dept of Health Professional Technologies', 'Bachelor of Science in Respiratory Therapy', 'BSRPT-LHR'),
    ('Faculty of Allied Health Sciences', '112201', 'Dept of Health Professional Technologies', 'Bachelor of Science in Surgical Technology', 'BSSUT-LHR'),
    ('Faculty of Allied Health Sciences', '112201', 'Dept of Health Professional Technologies', 'Bachelors of Science in Operation Theater', 'BSOPT-LHR'),
    ('Faculty of Allied Health Sciences', '112201', 'Dept of Health Professional Technologies', 'Doctor of Occupational Therapy', 'DOT-LHR'),
    ('Faculty of Allied Health Sciences', '112201', 'Dept of Health Professional Technologies', 'Postgraduate Diploma in Non-Invasive Orthopaedic', 'PGDNI-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', '1 Yr Transitional Diploma in MIT', 'TDMIT-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', '4 Years Bs (Medical Imaging Technology)', 'BSMDT-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Bachelor of Medical Imaging Sciences', 'BMIS-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Bachelor of Science Medicl Ultrasound Technology', 'BSCUT-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Bachelor of Science in Medical Ultrasound Technology', 'BSMUT-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Bachelor of Science in Medical Ultrasound and Sonography', 'BSMUS-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Bachelor of Science in Radiography and Imaging Technology', 'BSRIT-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Basics of Echocardiography', 'BOEC-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Certificate in Medical Ultrasound Technology', 'CMUT-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Diploma in Medical Diagnostic Ultrasound', 'DU-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Doctor of Philosophy in Diagnostic Ultrasound', 'DDU-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Doctor of Philosophy in Medical Imaging Technology', 'DMIT-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Doctor of Philosophy in Radiology', 'DR-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Doctor of Philosophy in Ultrasound Techn', 'DUT-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Extended Diploma In Medical Imaging Technology - 2 Years', 'EDMIT-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'M Phil in Fetal Medicine Ultrasound', 'PFM-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'M Phil in Obgyn Ultrasound', 'POGYN-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'M.D.Radiology', 'MDR-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'M.Phil Medical Ultrasound Technology', 'MMUT-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'M.Phil in Vascular Ultrasound', 'PVU-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Master of Philosophy in General Ultrasound', 'PGU-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Master of Philosophy in Musculoskeletal Ultrasound', 'MPMU-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Master of Science in  Diagnostic Ultrasound', 'MSDD-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Master of Science in Diagnostic Ultrasound', 'PDU-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Master of Science in Medical Imaging Technology', 'MSMIT-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Master of Science in Medical Imaging Technology - 2 Years', 'MSMDT-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Master of Science in Medical Ultrasound Technology - 2 Years', 'MSCMU-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Medical Imaging Doctor', 'MID-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'PhD.Medical Diagnotic ultrasound', 'DMDU-LHR'),
    ('Faculty of Allied Health Sciences', '112206', 'Dept of Radiological Sciences and MIT', 'Post Graduate Diploma in Medical Diagnostic Ultrasound', 'PGDU-LHR'),
    ('Faculty of Allied Health Sciences', '122206', 'Dept of Radiological Sciences and MIT', 'B.Sc Medical Ultrasound Technology', 'BMUT-LHR'),
    ('Faculty of Allied Health Sciences', '112212', 'Deptt. of Emerging Allied Health Tech.', 'Bachelor of Science in Cardiac Perfusion Technology', 'BSCPT-LHR'),
    ('Faculty of Allied Health Sciences', '112212', 'Deptt. of Emerging Allied Health Tech.', 'Bachelor of Science in Cardiac Technology', 'BSCAT-LHR'),
    ('Faculty of Allied Health Sciences', '112212', 'Deptt. of Emerging Allied Health Tech.', 'Bachelor of Science in Cardiovascular Technology', 'BSCVT-LHR'),
    ('Faculty of Allied Health Sciences', '112212', 'Deptt. of Emerging Allied Health Tech.', 'Bachelor of Science in Dermatology Technology', 'BSDIT-LHR'),
    ('Faculty of Allied Health Sciences', '112212', 'Deptt. of Emerging Allied Health Tech.', 'Bacheror of Science in Dialysis Technology', 'BSDT-LHR'),
    ('Faculty of Allied Health Sciences', '112212', 'Deptt. of Emerging Allied Health Tech.', 'Bachelor of Science in Endoscopy Technology', 'BSENT-LHR'),
    ('Faculty of Allied Health Sciences', '112212', 'Deptt. of Emerging Allied Health Tech.', 'Bachelor of Science in Neurophysiology Technology', 'BSNET-LHR'),
    ('Faculty of Allied Health Sciences', '112212', 'Deptt. of Emerging Allied Health Tech.', 'Bachelor of Science in Vascular Technology', 'BSVT-LHR'),
    ('Faculty of Allied Health Sciences', '113002', 'Lahore Institue of Future Education', 'Master of Arts in English Language Literature', 'MELT-LHR'),
    ('Faculty of Allied Health Sciences', '113002', 'Lahore Institue of Future Education', 'Master of Arts in English Language Literature', 'MAEL-LHR'),
    ('Faculty of Allied Health Sciences', '113002', 'Lahore Institue of Future Education', 'Masters of Philosophy in Applied Linguistics', 'PAL-LHR'),
    ('Faculty of Allied Health Sciences', '112204', 'Lahore School of Nursing', 'Bachelor of Science Post RN Nursing Program - 2 Years', 'PBSN-LHR'),
    ('Faculty of Allied Health Sciences', '112204', 'Lahore School of Nursing', 'Bachelor of Sciences in Nursing', 'BSN-LHR'),
    ('Faculty of Allied Health Sciences', '112204', 'Lahore School of Nursing', 'Master of Science in Nursing', 'MSN-LHR'),
    ('Faculty of Allied Health Sciences', '112204', 'Lahore School of Nursing', 'Occupational English Test', 'OET-LHR'),
    ('Faculty of Allied Health Sciences', '113005', 'NHNC', 'BSN POST RN (TWO YEAR)', 'BSNRN-LHR'),
    ('Faculty of Allied Health Sciences', '112210', 'Uni. Inst. of Food Science & Technology', 'Bachelor of Science in Dairy Technology', 'BSDAT-LHR'),
    ('Faculty of Allied Health Sciences', '112210', 'Uni. Inst. of Food Science & Technology', 'Bachelor of Science in Food Safety and Quality Management', 'BSFSQ-LHR'),
    ('Faculty of Allied Health Sciences', '112210', 'Uni. Inst. of Food Science & Technology', 'Bachelor of Science in Food Science and Technology', 'BSFST-LHR'),
    ('Faculty of Allied Health Sciences', '112210', 'Uni. Inst. of Food Science & Technology', 'Bachelor of Science in Meat Technology', 'BSFMT-LHR'),
    ('Faculty of Allied Health Sciences', '112210', 'Uni. Inst. of Food Science & Technology', 'Doctor of Philosophy in Food Science and Technology', 'DFST-LHR'),
    ('Faculty of Allied Health Sciences', '112210', 'Uni. Inst. of Food Science & Technology', 'Master of Philosophy in Dairy Science and Technology', 'PDST-LHR'),
    ('Faculty of Allied Health Sciences', '112210', 'Uni. Inst. of Food Science & Technology', 'Master of Philosophy in Food Sciences and Technology', 'PFST-LHR'),
    ('Faculty of Allied Health Sciences', '112210', 'Uni. Inst. of Food Science & Technology', 'Master of Philosophy in Meat Science and Technology', 'PMST-LHR'),
    ('Faculty of Allied Health Sciences', '112202', 'University Inst of Diet & Nutri Sciences', 'Bachelor of Dietetics and Nutritional Sciences', 'BDNS-LHR'),
    ('Faculty of Allied Health Sciences', '112202', 'University Inst of Diet & Nutri Sciences', 'Bachelor of Science (Hons) in Diet and Nutritional Sciences', 'BSHND-LHR'),
    ('Faculty of Allied Health Sciences', '112202', 'University Inst of Diet & Nutri Sciences', 'Bachelor of Science in Human Nutrition and Dietetics', 'BHND-LHR'),
    ('Faculty of Allied Health Sciences', '112202', 'University Inst of Diet & Nutri Sciences', 'Doctor of Diet and Nutritional Sciences', 'DDNS-LHR'),
    ('Faculty of Allied Health Sciences', '112202', 'University Inst of Diet & Nutri Sciences', 'Doctor of Philosophy in Human Nutrition and Dietetics', 'DHND-LHR'),
    ('Faculty of Allied Health Sciences', '112202', 'University Inst of Diet & Nutri Sciences', 'Master of Philosophy in Human Nuitrition and Dietetics', 'PHND-LHR'),
    ('Faculty of Allied Health Sciences', '112202', 'University Inst of Diet & Nutri Sciences', 'Practical Dietary Practices in Healthcare', 'PDPH-LHR'),
    ('Faculty of Allied Health Sciences', '112205', 'University Institute of Medical Lab Tech', 'Bachelor of Medical Laboratory Sciences', 'BMLS-LHR'),
    ('Faculty of Allied Health Sciences', '112205', 'University Institute of Medical Lab Tech', 'Bachelor of Science (Hons) in Medical Lab Technology', 'BSMLT-LHR'),
    ('Faculty of Allied Health Sciences', '112205', 'University Institute of Medical Lab Tech', 'Bachelor of Science in Medical Laboratory Technology', 'BMLT-LHR'),
    ('Faculty of Allied Health Sciences', '112205', 'University Institute of Medical Lab Tech', 'Certificate of Allied Health Professions', 'CAHPE-LHR'),
    ('Faculty of Allied Health Sciences', '112205', 'University Institute of Medical Lab Tech', 'Doctor of Medical Laboratory Sciences', 'DMLS-LHR'),
    ('Faculty of Allied Health Sciences', '112205', 'University Institute of Medical Lab Tech', 'Doctor of Philosophy in Immunology and Molecular Pathology', 'DIMP-LHR'),
    ('Faculty of Allied Health Sciences', '112205', 'University Institute of Medical Lab Tech', 'Doctor of Philosophy in Virology and Molecular Pathology', 'DVMP-LHR'),
    ('Faculty of Allied Health Sciences', '112205', 'University Institute of Medical Lab Tech', 'Master of Philosophy in Immunology and Molecular Pathology', 'PIMP-LHR'),
    ('Faculty of Allied Health Sciences', '112205', 'University Institute of Medical Lab Tech', 'Master of Philosophy in Virology and Molecular Pathology', 'PVMP-LHR'),
    ('Faculty of Allied Health Sciences', '112207', 'University Institute of Physical Therapy', 'Doctor of Philosophy in Physical Therapy', 'DPTH-LHR'),
    ('Faculty of Allied Health Sciences', '112207', 'University Institute of Physical Therapy', 'Doctor of Physical Therapy', 'DPT-LHR'),
    ('Faculty of Allied Health Sciences', '112207', 'University Institute of Physical Therapy', 'M.Phil Physical Therapy (Biomechanics)', 'MPPTB-LHR'),
    ('Faculty of Allied Health Sciences', '112207', 'University Institute of Physical Therapy', 'M.Phil Physical Therapy(Kinesiology)', 'MPPTK-LHR'),
    ('Faculty of Allied Health Sciences', '112207', 'University Institute of Physical Therapy', 'MS. Physical Therapy (Musculoskeletal)', 'MSPTM-LHR'),
    ('Faculty of Allied Health Sciences', '112207', 'University Institute of Physical Therapy', 'MS. Physical Therapy (Neurology)', 'MSPTN-LHR'),
    ('Faculty of Allied Health Sciences', '112207', 'University Institute of Physical Therapy', 'Master of Philosophy in Physical Therapy - Musculoskeletal', 'PPTM-LHR'),
    ('Faculty of Allied Health Sciences', '112207', 'University Institute of Physical Therapy', 'Master of Science in Cardiopulmonary Physical Therapy', 'MSCPT-LHR'),
    ('Faculty of Allied Health Sciences', '112207', 'University Institute of Physical Therapy', 'Master of Science in Physical Therapy (Geriatric Physical Therapy)', 'MSGPT-LHR'),
    ('Faculty of Allied Health Sciences', '112207', 'University Institute of Physical Therapy', 'Master of Science in Physical Therapy(Paediatric Physical Therapy)', 'MSPPT-LHR'),
    ('Faculty of Allied Health Sciences', '112207', 'University Institute of Physical Therapy', 'Master of Science in Physical Therapy(Women''s Health)', 'MSWH-LHR'),
    ('Faculty of Allied Health Sciences', '112207', 'University Institute of Physical Therapy', 'Master of Science in Sports Physical Therapy', 'MSSPT-LHR'),
    ('Faculty of Allied Health Sciences', '112208', 'University Institute of Public Health', 'Bachelor of Science in Public Health', 'BSPH-LHR'),
    ('Faculty of Allied Health Sciences', '112208', 'University Institute of Public Health', 'Doctor of Philosophy in Public Health', 'PPH-LHR'),
    ('Faculty of Allied Health Sciences', '112208', 'University Institute of Public Health', 'Master of  Public Health', 'MPH-LHR'),
    ('Faculty of Allied Health Sciences', '112208', 'University Institute of Public Health', 'Master of Philosophy in Public Health', 'PPHL-LHR'),
    ('Faculty of Natural Sciences', '111905', 'Department of Chemistry', 'Bachelor of Science in Applied Chemistry', 'BSAC-LHR'),
    ('Faculty of Natural Sciences', '111905', 'Department of Chemistry', 'Bachelor of Science in Chemistry ( 4 Years)', 'BSCHEM-LHR'),
    ('Faculty of Natural Sciences', '111905', 'Department of Chemistry', 'Bachelor of Science in Chemistry', 'BSCH-LHR'),
    ('Faculty of Natural Sciences', '111905', 'Department of Chemistry', 'Bachelor of Science in Chemistry with Artificial Intelligence', 'BSCAI-LHR'),
    ('Faculty of Natural Sciences', '111905', 'Department of Chemistry', 'Bachelor of Science in Forensic Chemistry', 'BSFC-LHR'),
    ('Faculty of Natural Sciences', '111905', 'Department of Chemistry', 'Doctor of Philosophy in Chemistry', 'DCHEM-LHR'),
    ('Faculty of Natural Sciences', '111905', 'Department of Chemistry', 'M. Phil Chemistry', 'MPCH-LHR'),
    ('Faculty of Natural Sciences', '111905', 'Department of Chemistry', 'M.Sc Chemistry ( 2 Years )', 'MCHEM-LHR'),
    ('Faculty of Natural Sciences', '111905', 'Department of Chemistry', 'Master of Philosophy in Chemistry', 'PCHEM-LHR'),
    ('Faculty of Natural Sciences', '111905', 'Department of Chemistry', 'Master of Science In Chemistry', 'MScCH-LHR'),
    ('Faculty of Natural Sciences', '111905', 'Department of Chemistry', 'Master of Science in Chemistry', 'MCH-LHR'),
    ('Faculty of Natural Sciences', '111906', 'Department of Environmental Sciences', 'Bachelor of Science Environmental Sciences', 'BSEN-LHR'),
    ('Faculty of Natural Sciences', '111906', 'Department of Environmental Sciences', 'Bachelor of Science in Deigraphic Information System', 'BSGIS-LHR'),
    ('Faculty of Natural Sciences', '111906', 'Department of Environmental Sciences', 'Bachelor of Science in Disadter Management with Artificial Intelligence', 'BSDMAI-LHR'),
    ('Faculty of Natural Sciences', '111906', 'Department of Environmental Sciences', 'Bachelor of Science in Health Safety and Enviroment', 'BSHSE-LHR'),
    ('Faculty of Natural Sciences', '111906', 'Department of Environmental Sciences', 'Doctor of Philosophy in Environmental Sciences', 'DEN-LHR'),
    ('Faculty of Natural Sciences', '111906', 'Department of Environmental Sciences', 'Master of Environmental Sciences', 'MEN-LHR'),
    ('Faculty of Natural Sciences', '111906', 'Department of Environmental Sciences', 'Master of Philosophy in Environmental Sciences', 'PEN-LHR'),
    ('Faculty of Natural Sciences', '111906', 'Department of Environmental Sciences', 'Master of Science in Environmental Sciences', 'MSEN-LHR'),
    ('Faculty of Natural Sciences', '111901', 'Department of Mathematics and Statistics', 'Bachelor of Science (Hons) in Mathematics', 'BSMAT-LHR'),
    ('Faculty of Natural Sciences', '111901', 'Department of Mathematics and Statistics', 'Bachelor of Science in Computational Finance', 'BSCF-LHR'),
    ('Faculty of Natural Sciences', '111901', 'Department of Mathematics and Statistics', 'Bachelor of Science in Mathematics for Data Science', 'BSMDS-LHR'),
    ('Faculty of Natural Sciences', '111901', 'Department of Mathematics and Statistics', 'Bachelor of Science in Mathematics with Artificial Intelligence', 'BSMAI-LHR'),
    ('Faculty of Natural Sciences', '111901', 'Department of Mathematics and Statistics', 'Bachelor of Science in Mathematics with Computer Science', 'BSMCS-LHR'),
    ('Faculty of Natural Sciences', '111901', 'Department of Mathematics and Statistics', 'Bachelor of Science in Statistics', 'BSST-LHR'),
    ('Faculty of Natural Sciences', '111901', 'Department of Mathematics and Statistics', 'Doctor Of Philosphy In Mathematics', 'DMAT-LHR'),
    ('Faculty of Natural Sciences', '111901', 'Department of Mathematics and Statistics', 'Master of Philosophy in Mathematics', 'PMT-LHR'),
    ('Faculty of Natural Sciences', '111901', 'Department of Mathematics and Statistics', 'Master of Philosophy in Mathematics', 'PHMAT-LHR'),
    ('Faculty of Natural Sciences', '111901', 'Department of Mathematics and Statistics', 'Master of Philosophy in Statistics', 'PST-LHR'),
    ('Faculty of Natural Sciences', '111902', 'Department of Physics', 'Bachelor of Science Computational Physics', 'BSCP-LHR'),
    ('Faculty of Natural Sciences', '111902', 'Department of Physics', 'Bachelor of Science in Bio Physics', 'BSBP-LHR'),
    ('Faculty of Natural Sciences', '111902', 'Department of Physics', 'Bachelor of Science in Engineering Physics', 'BSEP-LHR'),
    ('Faculty of Natural Sciences', '111902', 'Department of Physics', 'Bachelor of Science in Environmental Physics', 'BSENP-LHR'),
    ('Faculty of Natural Sciences', '111902', 'Department of Physics', 'Bachelor of Science in Geo Physics', 'BSGP-LHR'),
    ('Faculty of Natural Sciences', '111902', 'Department of Physics', 'Bachelor of Science in Medical Physics', 'BSPHM-LHR'),
    ('Faculty of Natural Sciences', '111902', 'Department of Physics', 'Bachelor of Science in Physics', 'BSP-LHR'),
    ('Faculty of Natural Sciences', '111902', 'Department of Physics', 'Bachelor of Science in Physics (Medical Physics)', 'BSMP-LHR'),
    ('Faculty of Natural Sciences', '111902', 'Department of Physics', 'Doctor of Philosphy in  Physics', 'DPH-LHR'),
    ('Faculty of Natural Sciences', '111902', 'Department of Physics', 'Master of Philosophy in Physics', 'PHP-LHR'),
    ('Faculty of Natural Sciences', '111902', 'Department of Physics', 'Master of Science in Physics', 'MPHY-LHR'),
    ('Faculty of Natural Sciences', '111902', 'Department of Physics', 'Master of Science in Physics', 'MSCPH-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachelor of Science (Hons) in Biochemistry', 'BBC-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachelor of Science in Biochemistry', 'BBCH-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachelor of Science in Biochemistry and Biotechnology', 'BSBB-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachelor of Science in Bioinformatics', 'BSBIOF-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachelor of Science in Bioinformatics with Artificial Intelligence', 'BSBAI-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachelor of Science in Biotechnology', 'BSBT-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachelor of Science in Botany', 'BSBOT-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachelor of Science in Clinical Biochemistry', 'BSCBT-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachelor of Science in Forensic Sciences', 'BSFRS-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachelor of Science in Industrial Biochemistry', 'BSIBT-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachelor of Science in Microbiology', 'BSM-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachelor of Science in Microbiology and Biotechnology', 'BSMIB-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachelor of Science in Molecular Biology', 'BSML-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachelor of Science in Molecular Biology and Biotechnology', 'BSMB-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachelor of Science in Molecular Pathology with Cytogenetics', 'BSMPC-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachelor of Science in Poultry Sciences', 'BSPS-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachelor of Science in Zoology', 'BSZOOL-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Bachlor of Scieces in Industrial Biotechnology', 'BSIB-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Doctor of Philosophy Microbiology', 'DMB-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Doctor of Philosophy in Biochemistry', 'DBC-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Doctor of Philosophy in Biotechnology', 'DBT-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Doctor of Philosophy in Botany', 'DBOT-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Doctor of Philosophy in Forensic Sciences', 'DFS-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Doctor of Philosophy in Molecular Biology', 'DML-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Doctor of Philosophy in Physiology', 'DPS-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Doctor of Philosophy in Zoology', 'DZOO-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'M.Phil Leading To Doctor of Philosophy in Physiology', 'PDPS-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'M.Phil Leading To Doctor of Philosophy in Biochemistry', 'PDBC-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'M.Phil in Zoology', 'PZOOL-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Philosophy Stem Cells and Rege', 'PSCRM-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Philosophy in Biochemistry', 'PBC-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Philosophy in Bioinformatics', 'MSBIOF-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Philosophy in Biotechnology', 'PBT-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Philosophy in Biotechnology', 'PBB-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Philosophy in Botany', 'PBOT-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Philosophy in Microbiology', 'PMC-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Philosophy in Molecular Biology', 'PML-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Philosophy in Physiology', 'PPS-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Philosphy in Forensic Sciences', 'PFS-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Science in Biochemistry', 'MBC-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Science in Biochemistry and Biotechnology', 'MBB-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Science in Biotechnology', 'MBT-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Science in Microbiology', 'MMC-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Science in Microbiology and Biotechnology', 'MSMIB-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Science in Molecular Biology', 'MMLB-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Science in Molecular Biology and Biotechnology', 'MMB-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Master of Science in Physiology', 'MPS-LHR'),
    ('Faculty of Natural Sciences', '111903', 'Institute of Molecular Biology & Biotech', 'Stem Cell Engineering', 'SCE-LHR'),
    ('Faculty of Natural Sciences', '111907', 'School of Pain & Regenrative Medicine', 'Bachelor of Science in Regenerartive Sciences', 'BSRGS-LHR'),
    ('Faculty of Natural Sciences', '111907', 'School of Pain & Regenrative Medicine', 'Dry Needling', 'DN-LHR'),
    ('Faculty of Natural Sciences', '111907', 'School of Pain & Regenrative Medicine', 'Postgraduate Diploma in Acupuncture', 'PGDAP-LHR'),
    ('Faculty of Natural Sciences', '111907', 'School of Pain & Regenrative Medicine', 'Postgraduate Diploma in Regenerative Sciences', 'PGDRS-LHR'),
    ('Faculty of Natural Sciences', '111907', 'School of Pain & Regenrative Medicine', 'Regenerative Aesthetics', 'RA-LHR'),
    ('Faculty of Natural Sciences', '111907', 'School of Pain & Regenrative Medicine', 'Regenerative Injections Therapy', 'RIT-LHR'),
    ('Faculty of Engineering', '111802', 'Department of Civil Engineering', 'Bachelor of Science in Civil Engineering', 'BSCE-LHR'),
    ('Faculty of Engineering', '111802', 'Department of Civil Engineering', 'Doctor of Philosphy in Civil Engineering', 'DCE-LHR'),
    ('Faculty of Engineering', '111802', 'Department of Civil Engineering', 'Master of Science in Civil Engineering', 'MSCE-LHR'),
    ('Faculty of Engineering', '111806', 'Department of Computer Engineering', 'Bachelor of Science in Computer Engineering', 'BSC-LHR'),
    ('Faculty of Engineering', '111806', 'Department of Computer Engineering', 'Master of Science in Computer Engineering', 'MSCPE-LHR'),
    ('Faculty of Engineering', '111801', 'Department of Electrical Engineering', 'Bachelor  of Science in Electrical Engineering', 'BSEE-LHR'),
    ('Faculty of Engineering', '111801', 'Department of Electrical Engineering', 'Bachelor in Electronics and Communication', 'BEEC-LHR'),
    ('Faculty of Engineering', '111801', 'Department of Electrical Engineering', 'Doctor of Philosphy in Electrical Engineering', 'DEE-LHR'),
    ('Faculty of Engineering', '111801', 'Department of Electrical Engineering', 'Master of Science in Electrical Engineering', 'MSEE-LHR'),
    ('Faculty of Engineering', '111803', 'Department of Mechanical Engineering', 'Bachelor of Science in Mechanical Engineering', 'BSME-LHR'),
    ('Faculty of Engineering', '111803', 'Department of Mechanical Engineering', 'Doctor of Philosophy in Mechanical Engineering', 'DME-LHR'),
    ('Faculty of Engineering', '111803', 'Department of Mechanical Engineering', 'Master of Science in Mechanical Engineering', 'MSME-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Associate Degree Program in Biomedical Engineering Technology', 'ADPBET-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Engineering Technologly(Biomedical)', 'BETB-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Engineering Technology (Civil).', 'BETC-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Engineering Technology (Mechanical)', 'BETM-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Engineering Technology in (Artificial Intelligence)', 'BETAI-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Engineering Technology in Information Security', 'BETIS-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Engineering Technology(Architectural)', 'BETA-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Science in Agriculture Engineering Technology', 'BSAGT-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Science in Architectural Engineering Technology', 'BSART-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'BS Biomedical Engineering Technology', 'BSBMD-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Science in Civil Engineering Technology', 'BSCET-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Science in Civil Technology', 'BTC-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Science in Civil Technology', 'BSCT-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Science in Construction Management', 'BSCM-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Science in Electrical Engineering Technology', 'BSEET-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Science in Electrical Technology', 'BTE-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Science in Electrical Technology', 'BSET-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Science in Electronics Technology', 'BSNT-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Science in Electronics Technology', 'BTN-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Science in Information Engineering Technology', 'BEIT-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Science in Information Engineering Technology', 'BSIET-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Science in Mechanical Engineering Technology', 'BSMET-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Science in Mechanical Technology', 'BTM-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Bachelor of Science in Mechanical Technology', 'BSMT-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Master of Science in Mechanical Engineering Technology', 'MSMET-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Professional Certificate in Digital Media Technology', 'PCDMT-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Professional Certificate in Industrial Automation Control', 'PCIAT-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Professional Certificate in Industrial Automation & Control', 'PCIAC-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Professional Certificate in Logistics Technology', 'PCLT-LHR'),
    ('Faculty of Engineering', '111804', 'Department of Technology', 'Professional Certificate in Vehicle Technology', 'PCVT-LHR'),
    ('Faculty of Engineering', '111805', 'Deptt of Electronics & Electrical System', 'Bachelor of Science in Communication and Information Technology', 'BSCIT-LHR'),
    ('Faculty of Engineering', '111805', 'Deptt of Electronics & Electrical System', 'Bachelor of Science in Electronics and Communication', 'BSEC-LHR'),
    ('Faculty of Engineering', '111805', 'Deptt of Electronics & Electrical System', 'Bachelor of Science in Electronics and Electrical Systems', 'BSEES-LHR'),
    ('Faculty of Engineering', '111805', 'Deptt of Electronics & Electrical System', 'Bachelor of Science in Power and Energy Systems', 'BSPES-LHR'),
    ('Faculty of Engineering', '111805', 'Deptt of Electronics & Electrical System', 'Master of Science in Electronics and Communication', 'MSEC-LHR'),
    ('Faculty of Engineering', '111805', 'Deptt of Electronics & Electrical System', 'Master of Science in Electronics and Electrical Systems', 'MSEES-LHR'),
    ('Faculty of CS & IT', '112001', 'Department of Computer Sciences & IT', 'BS(Cyber Security)', 'BSCBS-LHR'),
    ('Faculty of CS & IT', '112001', 'Department of Computer Sciences & IT', 'Bachelor of Science in Computer Science', 'BSCS-LHR'),
    ('Faculty of CS & IT', '112001', 'Department of Computer Sciences & IT', 'Bachelor of Science in Computer Science', 'BCS-LHR'),
    ('Faculty of CS & IT', '112001', 'Department of Computer Sciences & IT', 'Bachelor of Science in Information Technology', 'BSIT-LHR'),
    ('Faculty of CS & IT', '112001', 'Department of Computer Sciences & IT', 'Bachelor of Sciences in Data Science', 'BSDS-LHR'),
    ('Faculty of CS & IT', '112001', 'Department of Computer Sciences & IT', 'Doctor of Philosophy in Computer Science', 'DCS-LHR'),
    ('Faculty of CS & IT', '112001', 'Department of Computer Sciences & IT', 'Master in Computer Science', 'MCS-LHR'),
    ('Faculty of CS & IT', '112001', 'Department of Computer Sciences & IT', 'Master of Science in Computer Science', 'MSCS-LHR'),
    ('Faculty of CS & IT', '112001', 'Department of Computer Sciences & IT', 'Master of Science in Data Science', 'MSDS-LHR'),
    ('Faculty of CS & IT', '112001', 'Department of Computer Sciences & IT', 'Master of Science in Information Technology', 'MSCIT-LHR'),
    ('Faculty of CS & IT', '112001', 'Department of Computer Sciences & IT', 'Master of Science in Information Technology', 'MSIT-LHR'),
    ('Faculty of CS & IT', '112003', 'Department of Intelligent Systems', 'Associate Degree in Embedded Systems', 'ADPES-LHR'),
    ('Faculty of CS & IT', '112003', 'Department of Intelligent Systems', 'Bachelor of Science in Embedded Systems', 'BSES-LHR'),
    ('Faculty of CS & IT', '112003', 'Department of Intelligent Systems', 'Bachelor of Science in Robotics and Artificial Intelligence', 'BSRAI-LHR'),
    ('Faculty of CS & IT', '112002', 'Department of Software Engineering', 'Amazon FBA Wholesale', 'AFW-LHR'),
    ('Faculty of CS & IT', '112002', 'Department of Software Engineering', 'Amazon Online Arbitrage', 'AOA-LHR'),
    ('Faculty of CS & IT', '112002', 'Department of Software Engineering', 'Amazon Private Label', 'APL-LHR'),
    ('Faculty of CS & IT', '112002', 'Department of Software Engineering', 'Amazon Virtual Assistant (FBA Wholesale) 2 months', 'AVAWS-LHR'),
    ('Faculty of CS & IT', '112002', 'Department of Software Engineering', 'Amazon Virtual Assistant (Online Arbitrage) 2 Months', 'AVAOA-LHR'),
    ('Faculty of CS & IT', '112002', 'Department of Software Engineering', 'Amazon Virtual Assistant (Private Label) 2 months', 'AVAPL-LHR'),
    ('Faculty of CS & IT', '112002', 'Department of Software Engineering', 'Amazon Virtual Assistant Course (2 Months)', 'AVA-2-LHR'),
    ('Faculty of CS & IT', '112002', 'Department of Software Engineering', 'Bachelor of Science in Artificial Intelligence', 'BSAI-LHR'),
    ('Faculty of CS & IT', '112002', 'Department of Software Engineering', 'Bachelor of Science in Software Engineering', 'BSSE-LHR'),
    ('Faculty of CS & IT', '112002', 'Department of Software Engineering', 'Doctor of Philosophy in Software Engineering', 'DSE-LHR'),
    ('Faculty of CS & IT', '112002', 'Department of Software Engineering', 'Master of Science in Software Engineering', 'MSSE-LHR'),
    ('Faculty of CS & IT', '112002', 'Department of Software Engineering', 'Post Graduate Diploma in Enterprise Resource Planning', 'PGDERP-LHR'),
    ('Faculty of CS & IT', '112002', 'Department of Software Engineering', 'Shadowing Training Course (1 Month)', 'STC-LHR'),
    ('Faculty of Social Sciences', '111708', 'Department of Criminology', 'Bachelor of Science in Criminology and Criminal Justice', 'BSCCJ-LHR'),
    ('Faculty of Social Sciences', '111702', 'Department of Education', 'B.Ed. (Hons.) Elementary', 'BSED-LHR'),
    ('Faculty of Social Sciences', '111702', 'Department of Education', 'Bachelor of Education(B.ED Hons)', 'B.ED(H)-LHR'),
    ('Faculty of Social Sciences', '111702', 'Department of Education', 'Bachelor of Science In Education (Management)', 'BSEdM-LHR'),
    ('Faculty of Social Sciences', '111702', 'Department of Education', 'Bachelor of Science in Education (Educational Management)', 'BSEM-LHR'),
    ('Faculty of Social Sciences', '111702', 'Department of Education', 'Bachelor of Science in Education (with Business)', 'BSEB-LHR'),
    ('Faculty of Social Sciences', '111702', 'Department of Education', 'Bachelor of Science in Science Education', 'BSSEd-LHR'),
    ('Faculty of Social Sciences', '111702', 'Department of Education', 'Bachelor of Science in Special Education', 'BSSEDU-LHR'),
    ('Faculty of Social Sciences', '111702', 'Department of Education', 'Bachelor of Science in Stem Education', 'BSTEE-LHR'),
    ('Faculty of Social Sciences', '111702', 'Department of Education', 'Doctor of Philosophy in Education', 'DPE-LHR'),
    ('Faculty of Social Sciences', '111702', 'Department of Education', 'Master in Leadership Management', 'MALM-LHR'),
    ('Faculty of Social Sciences', '111702', 'Department of Education', 'Master of Arts Education (Early Childhood Education)', 'MAECE-LHR'),
    ('Faculty of Social Sciences', '111702', 'Department of Education', 'Master of Arts Education (Educational Management and Planning)', 'MAEMP-LHR'),
    ('Faculty of Social Sciences', '111702', 'Department of Education', 'Master of Arts Education (Special Education)', 'MASE-LHR'),
    ('Faculty of Social Sciences', '111702', 'Department of Education', 'Master of Philosophy in Education', 'PED-LHR'),
    ('Faculty of Social Sciences', '111702', 'Department of Education', 'Montessori Teachers Traning programme', 'MTTP-LHR'),
    ('Faculty of Social Sciences', '111703', 'Department of Islamic Studies', 'BS Islamic Studies with specialization in Quranic Sciences', 'BSQS-LHR'),
    ('Faculty of Social Sciences', '111703', 'Department of Islamic Studies', 'Bachelor of Science in Islamic Studies', 'BSIS-LHR'),
    ('Faculty of Social Sciences', '111703', 'Department of Islamic Studies', 'Doctor of Philosophy in Islamic Studies', 'DIS-LHR'),
    ('Faculty of Social Sciences', '111703', 'Department of Islamic Studies', 'Doctor of Philosophy in Islamic Studies', 'DI-LHR'),
    ('Faculty of Social Sciences', '111703', 'Department of Islamic Studies', 'Master of Philosophy in Islamic Studies', 'PIS-LHR'),
    ('Faculty of Social Sciences', '111707', 'Department of Sociology', 'Bachelor of Science in Sociology', 'BSSO-LHR'),
    ('Faculty of Social Sciences', '111707', 'Department of Sociology', 'Master of Philosophy in Sociology', 'MPSO-LHR'),
    ('Faculty of Social Sciences', '111305', 'Lahore School of Behavioural Sciences', 'Bachelor Of Science in Psychology(Applied Psychology)', 'BSPAP-LHR'),
    ('Faculty of Social Sciences', '111305', 'Lahore School of Behavioural Sciences', 'Bachelor Of Science in Psychology(Clinical Psychology)', 'BSPCP-LHR'),
    ('Faculty of Social Sciences', '111305', 'Lahore School of Behavioural Sciences', 'Bachelor of Science in Clinical Psychology', 'BSCPSY-LHR'),
    ('Faculty of Social Sciences', '111305', 'Lahore School of Behavioural Sciences', 'Bachelor of Science in Psychology', 'BSPSY-LHR'),
    ('Faculty of Social Sciences', '111305', 'Lahore School of Behavioural Sciences', 'Doctor of Philosophy in Psychology', 'DPSY-LHR'),
    ('Faculty of Social Sciences', '111305', 'Lahore School of Behavioural Sciences', 'Master of Philosophy in Applied Psychology', 'PHAP-LHR'),
    ('Faculty of Social Sciences', '111305', 'Lahore School of Behavioural Sciences', 'Master of Science in Clinical Psychology', 'MSCP-LHR'),
    ('Faculty of Social Sciences', '111305', 'Lahore School of Behavioural Sciences', 'Master of Science in Management', 'MSM-LHR'),
    ('Faculty of Social Sciences', '111305', 'Lahore School of Behavioural Sciences', 'Master of Science in Psychology', 'MPSY-LHR'),
    ('Faculty of Social Sciences', '111305', 'Lahore School of Behavioural Sciences', 'Master of Science in Total Quality Management', 'MSTQM-LHR'),
    ('Faculty of Social Sciences', '111705', 'School of Integrated Social Science', 'Bachelor of Science in Social Sciences', 'BSSS-LHR'),
    ('Faculty of Social Sciences', '111705', 'School of Integrated Social Science', 'Doctor of Philosophy in International Relations', 'DIR-LHR'),
    ('Faculty of Social Sciences', '111705', 'School of Integrated Social Science', 'Master of Philosophy in Intelligence and Security Studies', 'PHISS-LHR'),
    ('Faculty of Social Sciences', '111705', 'School of Integrated Social Science', 'Master of Philosophy in Political Science', 'PPTS-LHR'),
    ('Faculty of Management Sciences', '111701', 'Department of Economics', 'Bachelor Of Science In Business Economics: Banking And Finance', 'BSBEF-LHR'),
    ('Faculty of Management Sciences', '111701', 'Department of Economics', 'Bachelor of Science in Business Economics : Banking and Finance', 'BSBE-LHR'),
    ('Faculty of Management Sciences', '111701', 'Department of Economics', 'Bachelor of Science in Economics', 'BECON-LHR'),
    ('Faculty of Management Sciences', '111701', 'Department of Economics', 'Bachelor of Science in Economics and Finance', 'BECOF-LHR'),
    ('Faculty of Management Sciences', '111701', 'Department of Economics', 'Bachelor of Science in Economics with Data Analytics', 'BSEDA-LHR'),
    ('Faculty of Management Sciences', '111701', 'Department of Economics', 'Doctor of Philosophy in Economics', 'DECON-LHR'),
    ('Faculty of Management Sciences', '111701', 'Department of Economics', 'Master of  Business Economics: Banking and Finance', 'MGEBF-LHR'),
    ('Faculty of Management Sciences', '111701', 'Department of Economics', 'Master of  Business Economics: Banking and Finance', 'MBEBF-LHR'),
    ('Faculty of Management Sciences', '111701', 'Department of Economics', 'Master of  Economics', 'MSECON-LHR'),
    ('Faculty of Management Sciences', '111701', 'Department of Economics', 'Master of Philosophy in Economics', 'PECON-LHR'),
    ('Faculty of Management Sciences', '111701', 'Department of Economics', 'Master of Science in Economics', 'MECON-LHR'),
    ('Faculty of Management Sciences', '111303', 'Department of Information Management', 'Master Of Philosophy in Infromation Managment', 'PHIM-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'BA (Hons) HRM', 'BHR-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'BA (Hons) Marketing', 'BMK-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Bachelor of Business Administration', 'BBA2Y-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Bachelor of Business Administration (Hons)', 'BBA-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Bachelor of Business Studies', 'BBS-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Bachelor of Commerce', 'B.COM-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Bachelor of Commerce (Hons) - 4 Year', 'BCM-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Bachelor of Management in Textile and Fashion Designing', 'BFD-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Bachelor of Science in Business Analytics', 'BSBA-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Bachelor of Science in Digital Marketing', 'BSDM-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Bachelor of Science in Financial Technology (Fintech 3+1)', 'BSFNTUOB-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Bachelor of Science in Financial Technology (FINTECH)', 'BSFNT-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Bachelor of Science in Human Resource Analytics', 'BSHRA-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Bachelor of Science in Supply Chain Analytics', 'BSSCA-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Certificate in Accounting and Finance', 'CACF-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Certificate in Taxation', 'CTAX-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Diploma in Accounting and Finance', 'DIAF-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Diploma in Taxation', 'DTAX-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Doctor of Philosophy in Human Resource Development', 'DG-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Doctor of Philosophy in Management', 'DMG-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'MS Management', 'MSMG-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'MSc Human Resource Management', 'MHR-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'MSc in Applied Artificial Intelligence and Data Analytics(1+2)', 'MSAIDA-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master in Project Management', 'MPM-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master in Public Health', 'MHP-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Business Administration', 'MBA-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Business Administration - 1.5 Years - Project Managment', 'MBPM-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Business Administration - 1.5 Year', 'MBA1Y-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Business Administration - 1.5 Years - Project Management', 'MBEPM-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Business Administration - 1.5 Years-Innovation and', 'MBEIE-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Business Administration - 2 Years', 'MBA2Y-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Business Administration - 2.5  Years', 'MB2.5-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Business Administration - 3 Years', 'MBA3Y-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Business Administration - 3.5 Years', 'MB3.5-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Business Administration Executive', 'MBE-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Business Administration-After 4 Year BBA', 'MMA-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Management in Textile and Fashion Designing', 'MFD-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Philosophy in Management Sciences', 'PBA-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Public Management', 'PM-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Science in Digital Marketing', 'MSDM-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Science in E-Commerce', 'MSECM-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Science in Engineering Management', 'MSEM-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Science in Project Management', 'MSPM-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Science in Strategic Human Resource Analytics', 'MSHRA-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Master of Science in Supply Chain Management', 'MSSCM-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Masters of Science in Management Sciences', 'MSBA-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Post Graduate Diploma in Accounting and Finance', 'PGDAF-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Post Graduate Diploma in Business Administration', 'PGDBA-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Postgraduate Diploma for Corporate Directorship', 'PGDCD-LHR'),
    ('Faculty of Management Sciences', '111301', 'Lahore Business School', 'Postgraduate Diploma in Islamic Banking and Finance', 'PGIBF-LHR'),
    ('Faculty of Management Sciences', '111302', 'Lahore School of Aviation', 'Bachelor of Science in Aircraft Maintenance Technology', 'BSAMT-LHR'),
    ('Faculty of Management Sciences', '111302', 'Lahore School of Aviation', 'Bachelor of Science in Aviation Management (Hons)', 'BSAM-LHR'),
    ('Faculty of Management Sciences', '113001', 'School of Accountancy & Finance', 'Bachelor of Commerce (Associate Degree) - 2 Years', 'BCMA-LHR'),
    ('Faculty of Management Sciences', '113001', 'School of Accountancy & Finance', 'Bachelor of Commerce (Associate Degree) - 2 Years', 'BCOM-LHR'),
    ('Faculty of Management Sciences', '113001', 'School of Accountancy & Finance', 'Bachelor of Science in Accountancy and Finance', 'BAF-LHR'),
    ('Faculty of Management Sciences', '113001', 'School of Accountancy & Finance', 'Doctor of Philosophy in Accounting and Finance', 'DAF-LHR'),
    ('Faculty of Management Sciences', '113001', 'School of Accountancy & Finance', 'Master of Commerce', 'MCM-LHR'),
    ('Faculty of Management Sciences', '113001', 'School of Accountancy & Finance', 'Master of Commerce - 2 Years', 'M.COM-LHR'),
    ('Faculty of Management Sciences', '113001', 'School of Accountancy & Finance', 'Master of Philosophy in Accounting and Finance', 'PAF-LHR'),
    ('Faculty of Management Sciences', '113001', 'School of Accountancy & Finance', 'Master of Science in Accountancy and Finance - 3.5 Years (No', 'MSAF-LHR'),
    ('Faculty of Management Sciences', '113001', 'School of Accountancy & Finance', 'Master of Science in Accountancy and Finance - 3 Years (Comm', 'MSACT-LHR'),
    ('Faculty of Management Sciences', '113001', 'School of Accountancy & Finance', 'Master of Science in Accountancy and Finance - 2.5 Years (No', 'MSNC-LHR'),
    ('Faculty of Management Sciences', '113001', 'School of Accountancy & Finance', 'Master of Science in Accounting and Finance', 'MAF-LHR'),
    ('Faculty of Management Sciences', '113001', 'School of Accountancy & Finance', 'Master of Science in Accounting and Finance - 2 Years (Comme', 'MSA-LHR'),
    ('Faculty of Management Sciences', '113001', 'School of Accountancy & Finance', 'Master of Science in Accounting and Finance', 'MSCF-LHR'),
    ('Faculty of Management Sciences', '113001', 'School of Accountancy & Finance', 'Master of Science in Accounting and Finance - 1.5 Years', 'MSF-LHR'),
    ('Faculty of Management Sciences', '113001', 'School of Accountancy & Finance', 'Master of Science in Accounting and Finance - 2 Years (Non C', 'MSFN-LHR'),
    ('Faculty of Medicine & Dentistry', '112103', 'Department of Medical Education', 'Advanced Leadership and Health Management Training', 'ALHMT-LHR'),
    ('Faculty of Medicine & Dentistry', '112103', 'Department of Medical Education', 'Certificate in Basic Health Research', 'CBHR-LHR'),
    ('Faculty of Medicine & Dentistry', '112103', 'Department of Medical Education', 'Certificate in Health Professions Education', 'CHPE-LHR'),
    ('Faculty of Medicine & Dentistry', '112103', 'Department of Medical Education', 'Certificate in Health Research', 'CHR-LHR'),
    ('Faculty of Medicine & Dentistry', '112103', 'Department of Medical Education', 'Master of Science in Medical Education', 'MME-LHR'),
    ('Faculty of Medicine & Dentistry', '112104', 'Heath Professional Develoment & Lifelong', 'Basic Life Support', 'BLS-LHR'),
    ('Faculty of Medicine & Dentistry', '112104', 'Heath Professional Develoment & Lifelong', 'Certificate in LifeStyle Medicine', 'CLSM-LHR'),
    ('Faculty of Medicine & Dentistry', '112104', 'Heath Professional Develoment & Lifelong', 'Certified HealthCare Simulation Professional Certificate Course', 'CHSPCC-LHR'),
    ('Faculty of Medicine & Dentistry', '112104', 'Heath Professional Develoment & Lifelong', 'Diploma in Artifical Intelligence and Digital Health', 'DCAIDH-LHR'),
    ('Faculty of Medicine & Dentistry', '112104', 'Heath Professional Develoment & Lifelong', 'Fellowship in Aesthetic Medicine', 'FAM-LHR'),
    ('Faculty of Medicine & Dentistry', '112104', 'Heath Professional Develoment & Lifelong', 'Fellowship in Hair Transplant', 'FHT-LHR'),
    ('Faculty of Medicine & Dentistry', '112104', 'Heath Professional Develoment & Lifelong', 'International Family Medicine Training Program', 'CIFMTP-LHR'),
    ('Faculty of Medicine & Dentistry', '112104', 'Heath Professional Develoment & Lifelong', 'Minimum Service Delivery Standards', 'MSDSS-LHR'),
    ('Faculty of Medicine & Dentistry', '112104', 'Heath Professional Develoment & Lifelong', 'Post Graduate Certificate in Aesthetic Medicine', 'PGCAM-LHR'),
    ('Faculty of Medicine & Dentistry', '112104', 'Heath Professional Develoment & Lifelong', 'Post Graduate Certificate in Diabetology', 'PGCDB-LHR'),
    ('Faculty of Medicine & Dentistry', '112104', 'Heath Professional Develoment & Lifelong', 'Post Graduate Certificate in Family Medicine', 'PGCFM-LHR'),
    ('Faculty of Medicine & Dentistry', '112104', 'Heath Professional Develoment & Lifelong', 'Post Graduate Certificate in Vascular Access and Renal Transplantation', 'PGVRT-LHR'),
    ('Faculty of Medicine & Dentistry', '112104', 'Heath Professional Develoment & Lifelong', 'Trainning Pathways in Family Medicine', 'CITPFM-LHR'),
    ('Faculty of Medicine & Dentistry', '112102', 'University College of Dentistry', 'Bachelor of Dental Surgery', 'BDS-LHR'),
    ('Faculty of Medicine & Dentistry', '112102', 'University College of Dentistry', 'Diploma in Dental Hygienist', 'DDH-LHR'),
    ('Faculty of Medicine & Dentistry', '112102', 'University College of Dentistry', 'Diploma in Dental Technician', 'DDT-LHR'),
    ('Faculty of Medicine & Dentistry', '112102', 'University College of Dentistry', 'Fellow College of Surgeons and Physicians Orthodontics (FCPS)', 'FCPSO-LHR'),
    ('Faculty of Medicine & Dentistry', '112102', 'University College of Dentistry', 'Master of Dental Surgery', 'MDS-LHR'),
    ('Faculty of Medicine & Dentistry', '112102', 'University College of Dentistry', 'Master of Dental Surgery (Operative Dentistry)', 'MDSO-LHR'),
    ('Faculty of Medicine & Dentistry', '112102', 'University College of Dentistry', 'Master of Dental Surgery (Oral and Maxillo Facial Surgery)', 'MDSOMF-LHR'),
    ('Faculty of Medicine & Dentistry', '112102', 'University College of Dentistry', 'Master of Dental Surgery (Orthodontics)', 'MDSOR-LHR'),
    ('Faculty of Medicine & Dentistry', '112102', 'University College of Dentistry', 'Master of Dental Surgery (Prosthodontics)', 'MDSPRO-LHR'),
    ('Faculty of Medicine & Dentistry', '112101', 'University College of Medicine', 'Advanced Course in Assessment Practices', 'ACAP-LHR'),
    ('Faculty of Medicine & Dentistry', '112101', 'University College of Medicine', 'Bachelor of Medicine and Bachelor of Surgery', 'BMS-LHR'),
    ('Faculty of Medicine & Dentistry', '112101', 'University College of Medicine', 'Certificate in Clinical Education', 'CCE-LHR'),
    ('Faculty of Medicine & Dentistry', '112101', 'University College of Medicine', 'Diploma in Aesthetic Medicine', 'DAMA-LHR'),
    ('Faculty of Medicine & Dentistry', '112101', 'University College of Medicine', 'Diploma in Aesthetic Medicine', 'DAMB-LHR'),
    ('Faculty of Medicine & Dentistry', '112101', 'University College of Medicine', 'Foundation Semester', 'FS-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Bachelor of Pharmacy', 'BPH-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Bachelor of Science in Pharmacology and Toxicology', 'BSPT-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Bachelor of Sciences in Nutraceutical and Herbal Medicine', 'BSNHM-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Condensed', 'CD-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Doctor Of Philosophy In Pharmacology', 'DPHR-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Doctor of Pharmacy', 'PHARM D-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Doctor of Pharmacy', 'BPD-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Doctor of Philosophy in Pharmaceutical Chemistry', 'DPCH-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Doctor of Philosophy in Pharmaceutics', 'DPCU-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Doctor of Philosophy in Pharmacognosy', 'DPP-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Doctor of Philosophy in Pharmacy Practice', 'DHRP-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Foreign Licensing Exam Training for Pharmacists', 'FLETP-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'M. Phil Pharmacy Practice', 'PHRP-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'M.Phil PHARMACEUTICAL BIOTECHNOLOGY', 'PHBT-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Master of Philosophy in Clinical Pharmacy', 'PHCLP-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Master of Philosophy in Pharmaceutical Chemistry', 'PHRC-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Master of Philosophy in Pharmaceutical Technology', 'PHPHT-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Master of Philosophy in Pharmaceutics', 'PHRM-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Master of Philosophy in Pharmacognosy', 'PHMG-LHR'),
    ('Faculty of Pharmacy', '112301', 'Department of Pharmacy', 'Master of Philosophy in Pharmacology', 'PHMY-LHR'),
    ('Faculty of Language & Literature', '111602', 'Department of Urdu', 'Bachelor of Studies in Urdu', 'BSUR-LHR'),
    ('Faculty of Language & Literature', '111602', 'Department of Urdu', 'Master of Philosophy in Urdu', 'PUD-LHR'),
    ('Faculty of Language & Literature', '111601', 'Dept of English Language and Literature', 'Advanced Communication Skills: Public Speaking, Reading and Writing', 'ACS-LHR'),
    ('Faculty of Language & Literature', '111601', 'Dept of English Language and Literature', 'Bachelor of Science English Language and Communication', 'BSELC-LHR'),
    ('Faculty of Language & Literature', '111601', 'Dept of English Language and Literature', 'Bachelor of Science in English Language and Literature', 'BSELL-LHR'),
    ('Faculty of Language & Literature', '111601', 'Dept of English Language and Literature', 'Doctor of Philosophy in English', 'DET-LHR'),
    ('Faculty of Language & Literature', '111601', 'Dept of English Language and Literature', 'Master of Arts in English Language Teaching and Linguistics', 'MET-LHR'),
    ('Faculty of Language & Literature', '111601', 'Dept of English Language and Literature', 'Master of Arts in English Literature', 'MEL-LHR'),
    ('Faculty of Language & Literature', '111601', 'Dept of English Language and Literature', 'Master of Philosophy in English Applied Linguistics', 'PET-LHR'),
    ('Faculty of Language & Literature', '111601', 'Dept of English Language and Literature', 'Master of Philosophy in English Literature', 'PEL-LHR'),
    ('Faculty of Law', '111501', 'M.A Raoof College of Law', 'Bachelor of Arts in LLB (Hons)', 'BALLB-LHR'),
    ('Faculty of Law', '111501', 'M.A Raoof College of Law', 'Income Tax Return E-Filling Trainning', 'ITRET-LHR'),
    ('Faculty of Law', '111501', 'M.A Raoof College of Law', 'LLB 3 Years', 'LLB3Y-LHR'),
    ('Faculty of Arts & Architecture', '111401', 'School of Architecture', 'Bachelor of Architecture', 'BARCH-LHR'),
    ('Faculty of Arts & Architecture', '111401', 'School of Architecture', 'Bachelors of Interior Design', 'BINT-LHR'),
    ('Faculty of Arts & Architecture', '111401', 'School of Architecture', 'Certificate Course of Autodesk Autocad', 'CCAA-LHR'),
    ('Faculty of Arts & Architecture', '111401', 'School of Architecture', 'Certificate Course of Autodesk Revit Architecture', 'CCARA-LHR'),
    ('Faculty of Arts & Architecture', '111401', 'School of Architecture', 'Certificate Course of Drawing', 'CCDR-LHR'),
    ('Faculty of Arts & Architecture', '111401', 'School of Architecture', 'Certificate Course of Google Sketchup & Lumion', 'CCGSL-LHR'),
    ('Faculty of Arts & Architecture', '111401', 'School of Architecture', 'Certificate Course of Interior Design', 'CCID-LHR'),
    ('Faculty of Arts & Architecture', '111401', 'School of Architecture', 'Certificate Course of Painting', 'CCP-LHR'),
    ('Faculty of Arts & Architecture', '111401', 'School of Architecture', 'Master of Architecture', 'MARCH-LHR'),
    ('Faculty of Arts & Architecture', '111401', 'School of Architecture', 'Master of Interior Design', 'MIDN-LHR'),
    ('Faculty of Arts & Architecture', '111402', 'School of Creative Arts', 'Bachelor of  Fine Arts ( Visual Arts )', 'BFAV-LHR'),
    ('Faculty of Arts & Architecture', '111402', 'School of Creative Arts', 'Bachelor of Arts (Hons) in Film and Television', 'BAFT-LHR'),
    ('Faculty of Arts & Architecture', '111402', 'School of Creative Arts', 'Bachelor of Arts Mass Communication', 'BAMCM-LHR'),
    ('Faculty of Arts & Architecture', '111402', 'School of Creative Arts', 'Bachelor of Science (Hons) in Media Communication', 'BSMC-LHR'),
    ('Faculty of Arts & Architecture', '111402', 'School of Creative Arts', 'Bachelor of Science in  Animation and VFX', 'BSVFX-LHR'),
    ('Faculty of Arts & Architecture', '111402', 'School of Creative Arts', 'Bachelor of Science in Game Design', 'BSGD-LHR'),
    ('Faculty of Arts & Architecture', '111402', 'School of Creative Arts', 'Bachelor of Science in Media and Mass Communication', 'BSMMC-LHR'),
    ('Faculty of Arts & Architecture', '111402', 'School of Creative Arts', 'Bachelor of Science in Visual Communication Design', 'BSVCD-LHR'),
    ('Faculty of Arts & Architecture', '111402', 'School of Creative Arts', '', 'CGD-LHR'),
    ('Faculty of Arts & Architecture', '111402', 'School of Creative Arts', 'Doctor of Philosophy in Media and Communication Studies', 'DMMCS-LHR'),
    ('Faculty of Arts & Architecture', '111402', 'School of Creative Arts', 'Master of Philosophy in Media and Mass Communication', 'PMMC-LHR'),
    ('Faculty of Arts & Architecture', '111402', 'School of Creative Arts', 'Master of Philosophy in Media and Mass Communication (Professional Track)', 'PMMCP-LHR'),
    ('Faculty of Arts & Architecture', '111402', 'School of Creative Arts', 'Master of Philosophy in Media and Mass Communication (Research Track)', 'PMMCR-LHR'),
    ('Faculty of Arts & Architecture', '111402', 'School of Creative Arts', 'Master of Science in Mass Communication', 'MC-LHR'),
    ('Faculty of Arts & Architecture', '111402', 'School of Creative Arts', 'Master of Studies in Media and Communication Studies', 'MSMCS-LHR'),
    ('Faculty of Arts & Architecture', '111406', 'School of Fashion and Textile', 'Bachelor in Fashion and Styling', 'BFS-LHR'),
    ('Faculty of Arts & Architecture', '111406', 'School of Fashion and Textile', 'Bachelor of Studies in Fashion Design', 'BSFD-LHR')
) AS prog(faculty_name, department_code, department_name, program_name, program_abv)
INNER JOIN department_ids d ON d.faculty_name = prog.faculty_name
  AND d.department_name = prog.department_name
ON CONFLICT (department_id, program_name) DO NOTHING;